name: 'Set variables'
description: 'Set variables. Uses github context'
inputs:
  github_event_name:
    description: "Github event name"
    required: true
  github_action_name:
    description: "Github action name"
    required: true
outputs:
  data-aggregator-tag:
    description: "Set aggregator image tag"
    value: ${{ steps.set_variables.outputs.data-aggregator-tag }}
  gateway-api-tag:
    description: "Set API gateway image tag"
    value: ${{ steps.set_variables.outputs.gateway-api-tag }}
  data_aggregator_tags:
    description: "Aggregator tags"
    value: ${{ steps.set_variables.outputs.data_aggregator_tags }}
  gateway_api_tags:
    description: "API gateway tags"
    value: ${{ steps.set_variables.outputs.gateway_api_tags }}
runs:
  using: "composite"
  steps:
    - id: set_variables
      run: |
        echo "GITHUB_REF $GITHUB_REF"
        GH_EVENT_NAME=${{ inputs.github_event_name }}
        GH_ACTION_NAME=${{ inputs.github_action_name }}
        GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD | sed 's/\//-/g')
        GIT_COMMIT=$(git log -1 --format=%h )
        DOCKER_TAG=${GIT_BRANCH}-${GIT_COMMIT}
        if [[ ! -z $GH_EVENT_NAME ]] && [[ "$GH_EVENT_NAME" == "release" ]] ;then
            DOCKER_REPO_DATA_AGGREGATOR="eu.gcr.io/dev-container-repo/ng-data-aggregator"
            DOCKER_REPO_GATEWAY_API="eu.gcr.io/dev-container-repo/ng-gateway-api"

            case "${GH_EVENT_NAME}" in
                release)
                    DOCKER_REPO_DATA_AGGREGATOR="radixdlt/ng-data-aggregator"
                    DOCKER_REPO_GATEWAY_API="radixdlt/ng-gateway-api"
                    DATA_AGGREGATOR_TAGS="${DOCKER_REPO_DATA_AGGREGATOR}:${{ github.event.release.tag_name }}"
                    GATEWAY_API_TAGS="${DOCKER_REPO_GATEWAY_API}:${{ github.event.release.tag_name }}"
                ;;
                *)
                    echo "${GH_EVENT_NAME} not implemented yet"
                    exit 1
                ;;
            esac

            echo "DATA_AGGREGATOR_TAGS: $DATA_AGGREGATOR_TAGS"
            echo "GATEWAY_API_TAGS: $GATEWAY_API_TAGS"

            echo "::set-output name=data_aggregator_tags::$DATA_AGGREGATOR_TAGS"
            echo "::set-output name=gateway_api_tags::$GATEWAY_API_TAGS"
            echo "::set-output name=data-aggregator-tag::$DOCKER_TAG"
            echo "::set-output name=gateway-api-tag::$DOCKER_TAG"

        else
            DOCKER_REPO_DATA_AGGREGATOR="eu.gcr.io/dev-container-repo/ng-data-aggregator"
            DOCKER_REPO_GATEWAY_API="eu.gcr.io/dev-container-repo/ng-gateway-api"

            DATA_AGGREGATOR_TAGS="${DOCKER_REPO_DATA_AGGREGATOR}:${DOCKER_TAG}"
            GATEWAY_API_TAGS="${DOCKER_REPO_GATEWAY_API}:${DOCKER_TAG}"

            echo "DATA_AGGREGATOR_TAGS: $DATA_AGGREGATOR_TAGS"
            echo "GATEWAY_API_TAGS: $GATEWAY_API_TAGS"

            echo "::set-output name=data_aggregator_tags::$DATA_AGGREGATOR_TAGS"
            echo "::set-output name=gateway_api_tags::$GATEWAY_API_TAGS"
            echo "::set-output name=data-aggregator-tag::$DOCKER_TAG"
            echo "::set-output name=gateway-api-tag::$DOCKER_TAG"
        fi
      shell: bash
