/* Copyright 2021 Radix Publishing Ltd incorporated in Jersey (Channel Islands).
 *
 * Licensed under the Radix License, Version 1.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the License at:
 *
 * radixfoundation.org/licenses/LICENSE-v1
 *
 * The Licensor hereby grants permission for the Canonical version of the Work to be
 * published, distributed and used under or by reference to the Licensor’s trademark
 * Radix ® and use of any unregistered trade names, logos or get-up.
 *
 * The Licensor provides the Work (and each Contributor provides its Contributions) on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied,
 * including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT,
 * MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * Whilst the Work is capable of being deployed, used and adopted (instantiated) to create
 * a distributed ledger it is your responsibility to test and validate the code, together
 * with all logic and performance of that code under all foreseeable scenarios.
 *
 * The Licensor does not make or purport to make and hereby excludes liability for all
 * and any representation, warranty or undertaking in any form whatsoever, whether express
 * or implied, to any entity or person, including any representation, warranty or
 * undertaking, as to the functionality security use, value or other characteristics of
 * any distributed ledger nor in respect the functioning or value of any tokens which may
 * be created stored or transferred using the Work. The Licensor does not warrant that the
 * Work or any use of the Work complies with any law or regulation in any territory where
 * it may be implemented or used or that it will be appropriate for any specific purpose.
 *
 * Neither the licensor nor any current or former employees, officers, directors, partners,
 * trustees, representatives, agents, advisors, contractors, or volunteers of the Licensor
 * shall be liable for any direct or indirect, special, incidental, consequential or other
 * losses of any kind, in tort, contract or otherwise (including but not limited to loss
 * of revenue, income or profits, or loss of use or data, or loss of reputation, or loss
 * of any economic or other opportunity of whatsoever nature or howsoever arising), arising
 * out of or in connection with (without limitation of any use, misuse, of any ledger system
 * or use made or its functionality or any performance or operation of any code or protocol
 * caused by bugs or programming or logic errors or otherwise);
 *
 * A. any offer, purchase, holding, use, sale, exchange or transmission of any
 * cryptographic keys, tokens or assets created, exchanged, stored or arising from any
 * interaction with the Work;
 *
 * B. any failure in a transmission or loss of any token or assets keys or other digital
 * artefacts due to errors in transmission;
 *
 * C. bugs, hacks, logic errors or faults in the Work or any communication;
 *
 * D. system software or apparatus including but not limited to losses caused by errors
 * in holding or transmitting tokens by any third-party;
 *
 * E. breaches or failure of security including hacker attacks, loss or disclosure of
 * password, loss of private key, unauthorised use or misuse of such passwords or keys;
 *
 * F. any losses including loss of anticipated savings or other benefits resulting from
 * use of the Work or any changes to the Work (however implemented).
 *
 * You are solely responsible for; testing, validating and evaluation of all operation
 * logic, functionality, security and appropriateness of using the Work for any commercial
 * or non-commercial purpose and for any reproduction or redistribution by You of the
 * Work. You assume all risks associated with Your use of the Work and the exercise of
 * permissions under this License.
 */

﻿// <auto-generated />
using System;
using System.Numerics;
using DataAggregator.DependencyInjection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAggregator.Migrations
{
    [DbContext(typeof(AggregatorDbContext))]
    [Migration("20211125111815_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.Database.Models.Ledger.History.AccountResourceBalanceHistory", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long?>("ToStateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("to_state_version");

                    b.HasKey("AccountId", "ResourceId", "FromStateVersion");

                    b.HasIndex("AccountId", "FromStateVersion");

                    b.HasIndex("AccountId", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("IX_account_resource_balance_history_current_balance")
                        .HasFilter("to_state_version is null");

                    b.HasIndex("ResourceId", "FromStateVersion");

                    b.HasIndex("ResourceId", "AccountId", "FromStateVersion");

                    b.ToTable("account_resource_balance_history");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.History.ResourceSupplyHistory", b =>
                {
                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long?>("ToStateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("to_state_version");

                    b.HasKey("ResourceId", "FromStateVersion");

                    b.HasIndex("ResourceId")
                        .IsUnique()
                        .HasDatabaseName("IX_resource_supply_history_current_supply")
                        .HasFilter("to_state_version is null");

                    b.ToTable("resource_supply_history");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.History.ValidatorStakeHistory", b =>
                {
                    b.Property<long>("ValidatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("validator_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long?>("ToStateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("to_state_version");

                    b.HasKey("ValidatorId", "FromStateVersion");

                    b.HasIndex("ValidatorId")
                        .IsUnique()
                        .HasDatabaseName("IX_validator_stake_history_current_supply")
                        .HasFilter("to_state_version is null");

                    b.ToTable("validator_stake_history");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.LedgerOperationGroup", b =>
                {
                    b.Property<long>("ResultantStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("state_version");

                    b.Property<int>("OperationGroupIndex")
                        .HasColumnType("integer")
                        .HasColumnName("operation_group_index");

                    b.HasKey("ResultantStateVersion", "OperationGroupIndex");

                    b.ToTable("operation_groups");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.LedgerTransaction", b =>
                {
                    b.Property<long>("ResultantStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("state_version");

                    b.Property<long?>("EndOfEpochRound")
                        .HasColumnType("bigint")
                        .HasColumnName("end_of_round");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint")
                        .HasColumnName("epoch");

                    b.Property<BigInteger>("FeePaid")
                        .HasPrecision(1000)
                        .HasColumnType("numeric(1000)")
                        .HasColumnName("fee_paid");

                    b.Property<long>("IndexInEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("index_in_epoch");

                    b.Property<bool>("IsEndOfEpoch")
                        .HasColumnType("boolean")
                        .HasColumnName("is_end_of_epoch");

                    b.Property<bool>("IsOnlyRoundChange")
                        .HasColumnType("boolean")
                        .HasColumnName("is_only_round_change");

                    b.Property<byte[]>("Message")
                        .HasColumnType("bytea")
                        .HasColumnName("message");

                    b.Property<byte[]>("SignedBy")
                        .HasColumnType("bytea")
                        .HasColumnName("signed_by");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<byte[]>("TransactionAccumulator")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("transaction_accumulator");

                    b.Property<byte[]>("TransactionIdentifierHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("transaction_id");

                    b.HasKey("ResultantStateVersion");

                    b.HasAlternateKey("TransactionAccumulator");

                    b.HasAlternateKey("TransactionIdentifierHash");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Epoch", "EndOfEpochRound")
                        .IsUnique()
                        .HasFilter("end_of_round IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Epoch", "EndOfEpochRound"), new[] { "Timestamp" });

                    b.ToTable("ledger_transactions");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Normalization.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Normalization.Resource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<byte[]>("RadixEngineAddress")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("engine_address");

                    b.Property<string>("ResourceIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rri");

                    b.HasKey("Id");

                    b.HasIndex("ResourceIdentifier")
                        .IsUnique();

                    b.ToTable("resources");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Normalization.Validator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("validators");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Substates.AccountResourceBalanceSubstate", b =>
                {
                    b.Property<long>("UpStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("up_state_version");

                    b.Property<int>("UpOperationGroupIndex")
                        .HasColumnType("integer")
                        .HasColumnName("up_operation_group_index");

                    b.Property<int>("UpOperationIndexInGroup")
                        .HasColumnType("integer")
                        .HasColumnName("up_operation_index_in_group");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<BigInteger>("Amount")
                        .HasPrecision(1000)
                        .HasColumnType("numeric(1000)")
                        .HasColumnName("amount");

                    b.Property<int?>("DownOperationGroupIndex")
                        .HasColumnType("integer")
                        .HasColumnName("down_operation_group_index");

                    b.Property<int?>("DownOperationIndexInGroup")
                        .HasColumnType("integer")
                        .HasColumnName("down_operation_index_in_group");

                    b.Property<long?>("DownStateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("down_state_version");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<byte[]>("SubstateIdentifier")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("substate_identifier");

                    b.HasKey("UpStateVersion", "UpOperationGroupIndex", "UpOperationIndexInGroup");

                    b.HasAlternateKey("SubstateIdentifier");

                    b.HasIndex("AccountId", "ResourceId");

                    b.HasIndex("DownStateVersion", "DownOperationGroupIndex");

                    b.HasIndex("ResourceId", "AccountId");

                    b.HasIndex("AccountId", "ResourceId", "Amount")
                        .HasDatabaseName("IX_account_resource_balance_substate_current_unspent_utxos")
                        .HasFilter("down_state_version is null");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("AccountId", "ResourceId", "Amount"), new[] { "SubstateIdentifier" });

                    b.ToTable("account_resource_balance_substates");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Substates.AccountStakeOwnershipBalanceSubstate", b =>
                {
                    b.Property<long>("UpStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("up_state_version");

                    b.Property<int>("UpOperationGroupIndex")
                        .HasColumnType("integer")
                        .HasColumnName("up_operation_group_index");

                    b.Property<int>("UpOperationIndexInGroup")
                        .HasColumnType("integer")
                        .HasColumnName("up_operation_index_in_group");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<BigInteger>("Amount")
                        .HasPrecision(1000)
                        .HasColumnType("numeric(1000)")
                        .HasColumnName("amount");

                    b.Property<int?>("DownOperationGroupIndex")
                        .HasColumnType("integer")
                        .HasColumnName("down_operation_group_index");

                    b.Property<int?>("DownOperationIndexInGroup")
                        .HasColumnType("integer")
                        .HasColumnName("down_operation_index_in_group");

                    b.Property<long?>("DownStateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("down_state_version");

                    b.Property<byte[]>("SubstateIdentifier")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("substate_identifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<long>("ValidatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("validator_id");

                    b.HasKey("UpStateVersion", "UpOperationGroupIndex", "UpOperationIndexInGroup");

                    b.HasAlternateKey("SubstateIdentifier");

                    b.HasIndex("AccountId", "ValidatorId");

                    b.HasIndex("DownStateVersion", "DownOperationGroupIndex");

                    b.HasIndex("ValidatorId", "AccountId");

                    b.ToTable("account_stake_ownership_balance_substates");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Substates.AccountXrdStakeBalanceSubstate", b =>
                {
                    b.Property<long>("UpStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("up_state_version");

                    b.Property<int>("UpOperationGroupIndex")
                        .HasColumnType("integer")
                        .HasColumnName("up_operation_group_index");

                    b.Property<int>("UpOperationIndexInGroup")
                        .HasColumnType("integer")
                        .HasColumnName("up_operation_index_in_group");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<BigInteger>("Amount")
                        .HasPrecision(1000)
                        .HasColumnType("numeric(1000)")
                        .HasColumnName("amount");

                    b.Property<int?>("DownOperationGroupIndex")
                        .HasColumnType("integer")
                        .HasColumnName("down_operation_group_index");

                    b.Property<int?>("DownOperationIndexInGroup")
                        .HasColumnType("integer")
                        .HasColumnName("down_operation_index_in_group");

                    b.Property<long?>("DownStateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("down_state_version");

                    b.Property<byte[]>("SubstateIdentifier")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("substate_identifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<long?>("UnlockEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("unlock_epoch");

                    b.Property<long>("ValidatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("validator_id");

                    b.HasKey("UpStateVersion", "UpOperationGroupIndex", "UpOperationIndexInGroup");

                    b.HasAlternateKey("SubstateIdentifier");

                    b.HasIndex("AccountId", "ValidatorId");

                    b.HasIndex("DownStateVersion", "DownOperationGroupIndex");

                    b.HasIndex("ValidatorId", "AccountId");

                    b.ToTable("account_xrd_stake_balance_substates");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Substates.ResourceDataSubstate", b =>
                {
                    b.Property<long>("UpStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("up_state_version");

                    b.Property<int>("UpOperationGroupIndex")
                        .HasColumnType("integer")
                        .HasColumnName("up_operation_group_index");

                    b.Property<int>("UpOperationIndexInGroup")
                        .HasColumnType("integer")
                        .HasColumnName("up_operation_index_in_group");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DownOperationGroupIndex")
                        .HasColumnType("integer")
                        .HasColumnName("down_operation_group_index");

                    b.Property<int?>("DownOperationIndexInGroup")
                        .HasColumnType("integer")
                        .HasColumnName("down_operation_index_in_group");

                    b.Property<long?>("DownStateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("down_state_version");

                    b.Property<BigInteger?>("Granularity")
                        .HasPrecision(1000)
                        .HasColumnType("numeric(1000)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("IsMutable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<byte[]>("SubstateIdentifier")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("substate_identifier");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("UpStateVersion", "UpOperationGroupIndex", "UpOperationIndexInGroup");

                    b.HasAlternateKey("SubstateIdentifier");

                    b.HasIndex("ResourceId");

                    b.HasIndex("DownStateVersion", "DownOperationGroupIndex");

                    b.ToTable("resource_data_substates");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Substates.ValidatorDataSubstate", b =>
                {
                    b.Property<long>("UpStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("up_state_version");

                    b.Property<int>("UpOperationGroupIndex")
                        .HasColumnType("integer")
                        .HasColumnName("up_operation_group_index");

                    b.Property<int>("UpOperationIndexInGroup")
                        .HasColumnType("integer")
                        .HasColumnName("up_operation_index_in_group");

                    b.Property<int?>("DownOperationGroupIndex")
                        .HasColumnType("integer")
                        .HasColumnName("down_operation_group_index");

                    b.Property<int?>("DownOperationIndexInGroup")
                        .HasColumnType("integer")
                        .HasColumnName("down_operation_index_in_group");

                    b.Property<long?>("DownStateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("down_state_version");

                    b.Property<long?>("EffectiveEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("effective_epoch");

                    b.Property<byte[]>("SubstateIdentifier")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("substate_identifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<long>("ValidatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("validator_id");

                    b.HasKey("UpStateVersion", "UpOperationGroupIndex", "UpOperationIndexInGroup");

                    b.HasAlternateKey("SubstateIdentifier");

                    b.HasIndex("ValidatorId");

                    b.HasIndex("DownStateVersion", "DownOperationGroupIndex");

                    b.ToTable("validator_data_substates");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Substates.ValidatorStakeBalanceSubstate", b =>
                {
                    b.Property<long>("UpStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("up_state_version");

                    b.Property<int>("UpOperationGroupIndex")
                        .HasColumnType("integer")
                        .HasColumnName("up_operation_group_index");

                    b.Property<int>("UpOperationIndexInGroup")
                        .HasColumnType("integer")
                        .HasColumnName("up_operation_index_in_group");

                    b.Property<BigInteger>("Amount")
                        .HasPrecision(1000)
                        .HasColumnType("numeric(1000)")
                        .HasColumnName("amount");

                    b.Property<int?>("DownOperationGroupIndex")
                        .HasColumnType("integer")
                        .HasColumnName("down_operation_group_index");

                    b.Property<int?>("DownOperationIndexInGroup")
                        .HasColumnType("integer")
                        .HasColumnName("down_operation_index_in_group");

                    b.Property<long?>("DownStateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("down_state_version");

                    b.Property<long>("EndOfEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("epoch");

                    b.Property<byte[]>("SubstateIdentifier")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("substate_identifier");

                    b.Property<long>("ValidatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("validator_id");

                    b.HasKey("UpStateVersion", "UpOperationGroupIndex", "UpOperationIndexInGroup");

                    b.HasAlternateKey("SubstateIdentifier");

                    b.HasIndex("ValidatorId");

                    b.HasIndex("DownStateVersion", "DownOperationGroupIndex");

                    b.HasIndex("EndOfEpoch", "ValidatorId")
                        .IsUnique();

                    b.ToTable("validator_stake_balance_substates");
                });

            modelBuilder.Entity("Common.Database.Models.Node", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<bool>("EnabledForIndexing")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled_for_indexing");

                    b.Property<decimal>("TrustWeighting")
                        .HasColumnType("numeric")
                        .HasColumnName("trust_weighting");

                    b.HasKey("Name");

                    b.ToTable("nodes");
                });

            modelBuilder.Entity("Common.Database.Models.RawTransaction", b =>
                {
                    b.Property<byte[]>("TransactionIdentifierHash")
                        .HasColumnType("bytea")
                        .HasColumnName("transaction_id");

                    b.Property<byte[]>("Payload")
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("SubmittedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_timestamp");

                    b.HasKey("TransactionIdentifierHash");

                    b.ToTable("raw_transactions");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.History.AccountResourceBalanceHistory", b =>
                {
                    b.HasOne("Common.Database.Models.Ledger.Normalization.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Database.Models.Ledger.Normalization.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Common.Database.Models.Ledger.History.BalanceEntry", "BalanceEntry", b1 =>
                        {
                            b1.Property<long>("AccountResourceBalanceHistoryAccountId")
                                .HasColumnType("bigint");

                            b1.Property<long>("AccountResourceBalanceHistoryResourceId")
                                .HasColumnType("bigint");

                            b1.Property<long>("AccountResourceBalanceHistoryFromStateVersion")
                                .HasColumnType("bigint");

                            b1.Property<BigInteger>("Balance")
                                .HasPrecision(1000)
                                .HasColumnType("numeric(1000)")
                                .HasColumnName("balance");

                            b1.HasKey("AccountResourceBalanceHistoryAccountId", "AccountResourceBalanceHistoryResourceId", "AccountResourceBalanceHistoryFromStateVersion");

                            b1.ToTable("account_resource_balance_history");

                            b1.WithOwner()
                                .HasForeignKey("AccountResourceBalanceHistoryAccountId", "AccountResourceBalanceHistoryResourceId", "AccountResourceBalanceHistoryFromStateVersion");
                        });

                    b.Navigation("Account");

                    b.Navigation("BalanceEntry")
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.History.ResourceSupplyHistory", b =>
                {
                    b.HasOne("Common.Database.Models.Ledger.Normalization.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Common.Database.Models.Ledger.History.ResourceSupply", "ResourceSupply", b1 =>
                        {
                            b1.Property<long>("ResourceSupplyHistoryResourceId")
                                .HasColumnType("bigint");

                            b1.Property<long>("ResourceSupplyHistoryFromStateVersion")
                                .HasColumnType("bigint");

                            b1.Property<BigInteger>("TotalBurnt")
                                .HasPrecision(1000)
                                .HasColumnType("numeric(1000)")
                                .HasColumnName("total_burnt");

                            b1.Property<BigInteger>("TotalMinted")
                                .HasPrecision(1000)
                                .HasColumnType("numeric(1000)")
                                .HasColumnName("total_minted");

                            b1.Property<BigInteger>("TotalSupply")
                                .HasPrecision(1000)
                                .HasColumnType("numeric(1000)")
                                .HasColumnName("total_supply");

                            b1.HasKey("ResourceSupplyHistoryResourceId", "ResourceSupplyHistoryFromStateVersion");

                            b1.ToTable("resource_supply_history");

                            b1.WithOwner()
                                .HasForeignKey("ResourceSupplyHistoryResourceId", "ResourceSupplyHistoryFromStateVersion");
                        });

                    b.Navigation("Resource");

                    b.Navigation("ResourceSupply")
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.History.ValidatorStakeHistory", b =>
                {
                    b.HasOne("Common.Database.Models.Ledger.Normalization.Validator", "Validator")
                        .WithMany()
                        .HasForeignKey("ValidatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Common.Database.Models.Ledger.History.StakeSnapshot", "StakeSnapshot", b1 =>
                        {
                            b1.Property<long>("ValidatorStakeHistoryValidatorId")
                                .HasColumnType("bigint");

                            b1.Property<long>("ValidatorStakeHistoryFromStateVersion")
                                .HasColumnType("bigint");

                            b1.Property<BigInteger>("TotalExitingXrdStake")
                                .HasPrecision(1000)
                                .HasColumnType("numeric(1000)")
                                .HasColumnName("total_exiting_stake_ownership");

                            b1.Property<BigInteger>("TotalPreparedUnstakeOwnership")
                                .HasPrecision(1000)
                                .HasColumnType("numeric(1000)")
                                .HasColumnName("total_prepared_unstake_ownership");

                            b1.Property<BigInteger>("TotalPreparedXrdStake")
                                .HasPrecision(1000)
                                .HasColumnType("numeric(1000)")
                                .HasColumnName("total_prepared_xrd_stake");

                            b1.Property<BigInteger>("TotalStakeOwnership")
                                .HasPrecision(1000)
                                .HasColumnType("numeric(1000)")
                                .HasColumnName("total_stake_ownership");

                            b1.Property<BigInteger>("TotalXrdStake")
                                .HasPrecision(1000)
                                .HasColumnType("numeric(1000)")
                                .HasColumnName("total_xrd_staked");

                            b1.HasKey("ValidatorStakeHistoryValidatorId", "ValidatorStakeHistoryFromStateVersion");

                            b1.ToTable("validator_stake_history");

                            b1.WithOwner()
                                .HasForeignKey("ValidatorStakeHistoryValidatorId", "ValidatorStakeHistoryFromStateVersion");
                        });

                    b.Navigation("StakeSnapshot")
                        .IsRequired();

                    b.Navigation("Validator");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.LedgerOperationGroup", b =>
                {
                    b.HasOne("Common.Database.Models.Ledger.LedgerTransaction", "LedgerTransaction")
                        .WithMany()
                        .HasForeignKey("ResultantStateVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Common.Database.Models.Ledger.InferredAction", "InferredAction", b1 =>
                        {
                            b1.Property<long>("LedgerOperationGroupResultantStateVersion")
                                .HasColumnType("bigint");

                            b1.Property<int>("LedgerOperationGroupOperationGroupIndex")
                                .HasColumnType("integer");

                            b1.Property<BigInteger?>("Amount")
                                .HasPrecision(1000)
                                .HasColumnType("numeric(1000)")
                                .HasColumnName("inferred_action_amount");

                            b1.Property<string>("FromAddress")
                                .HasColumnType("text")
                                .HasColumnName("inferred_action_from");

                            b1.Property<string>("ResourceIdentifier")
                                .HasColumnType("text")
                                .HasColumnName("inferred_action_rri");

                            b1.Property<string>("ToAddress")
                                .HasColumnType("text")
                                .HasColumnName("inferred_action_to");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("inferred_action_type");

                            b1.HasKey("LedgerOperationGroupResultantStateVersion", "LedgerOperationGroupOperationGroupIndex");

                            b1.ToTable("operation_groups");

                            b1.WithOwner()
                                .HasForeignKey("LedgerOperationGroupResultantStateVersion", "LedgerOperationGroupOperationGroupIndex");
                        });

                    b.Navigation("InferredAction");

                    b.Navigation("LedgerTransaction");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.LedgerTransaction", b =>
                {
                    b.HasOne("Common.Database.Models.RawTransaction", "RawTransaction")
                        .WithMany()
                        .HasForeignKey("TransactionIdentifierHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawTransaction");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Substates.AccountResourceBalanceSubstate", b =>
                {
                    b.HasOne("Common.Database.Models.Ledger.Normalization.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Database.Models.Ledger.Normalization.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Database.Models.Ledger.LedgerOperationGroup", "DownOperationGroup")
                        .WithMany()
                        .HasForeignKey("DownStateVersion", "DownOperationGroupIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_account_resource_balance_substate_down_operation_group");

                    b.HasOne("Common.Database.Models.Ledger.LedgerOperationGroup", "UpOperationGroup")
                        .WithMany()
                        .HasForeignKey("UpStateVersion", "UpOperationGroupIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_account_resource_balance_substate_up_operation_group");

                    b.Navigation("Account");

                    b.Navigation("DownOperationGroup");

                    b.Navigation("Resource");

                    b.Navigation("UpOperationGroup");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Substates.AccountStakeOwnershipBalanceSubstate", b =>
                {
                    b.HasOne("Common.Database.Models.Ledger.Normalization.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Database.Models.Ledger.Normalization.Validator", "Validator")
                        .WithMany()
                        .HasForeignKey("ValidatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Database.Models.Ledger.LedgerOperationGroup", "DownOperationGroup")
                        .WithMany()
                        .HasForeignKey("DownStateVersion", "DownOperationGroupIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_account_stake_ownership_balance_substate_down_operation_group");

                    b.HasOne("Common.Database.Models.Ledger.LedgerOperationGroup", "UpOperationGroup")
                        .WithMany()
                        .HasForeignKey("UpStateVersion", "UpOperationGroupIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_account_stake_ownership_balance_substate_up_operation_group");

                    b.Navigation("Account");

                    b.Navigation("DownOperationGroup");

                    b.Navigation("UpOperationGroup");

                    b.Navigation("Validator");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Substates.AccountXrdStakeBalanceSubstate", b =>
                {
                    b.HasOne("Common.Database.Models.Ledger.Normalization.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Database.Models.Ledger.Normalization.Validator", "Validator")
                        .WithMany()
                        .HasForeignKey("ValidatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Database.Models.Ledger.LedgerOperationGroup", "DownOperationGroup")
                        .WithMany()
                        .HasForeignKey("DownStateVersion", "DownOperationGroupIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_account_xrd_stake_balance_substate_down_operation_group");

                    b.HasOne("Common.Database.Models.Ledger.LedgerOperationGroup", "UpOperationGroup")
                        .WithMany()
                        .HasForeignKey("UpStateVersion", "UpOperationGroupIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_account_xrd_stake_balance_substate_up_operation_group");

                    b.Navigation("Account");

                    b.Navigation("DownOperationGroup");

                    b.Navigation("UpOperationGroup");

                    b.Navigation("Validator");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Substates.ResourceDataSubstate", b =>
                {
                    b.HasOne("Common.Database.Models.Ledger.Normalization.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Database.Models.Ledger.LedgerOperationGroup", "DownOperationGroup")
                        .WithMany()
                        .HasForeignKey("DownStateVersion", "DownOperationGroupIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_resource_data_substate_down_operation_group");

                    b.HasOne("Common.Database.Models.Ledger.LedgerOperationGroup", "UpOperationGroup")
                        .WithMany()
                        .HasForeignKey("UpStateVersion", "UpOperationGroupIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_resource_data_substate_up_operation_group");

                    b.Navigation("DownOperationGroup");

                    b.Navigation("Resource");

                    b.Navigation("UpOperationGroup");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Substates.ValidatorDataSubstate", b =>
                {
                    b.HasOne("Common.Database.Models.Ledger.Normalization.Validator", "Validator")
                        .WithMany()
                        .HasForeignKey("ValidatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Database.Models.Ledger.LedgerOperationGroup", "DownOperationGroup")
                        .WithMany()
                        .HasForeignKey("DownStateVersion", "DownOperationGroupIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_validator_data_substate_down_operation_group");

                    b.HasOne("Common.Database.Models.Ledger.LedgerOperationGroup", "UpOperationGroup")
                        .WithMany()
                        .HasForeignKey("UpStateVersion", "UpOperationGroupIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_validator_data_substate_up_operation_group");

                    b.OwnsOne("Common.Database.Models.Ledger.Substates.PreparedValidatorFee", "PreparedValidatorFee", b1 =>
                        {
                            b1.Property<long>("ValidatorDataSubstateUpStateVersion")
                                .HasColumnType("bigint");

                            b1.Property<int>("ValidatorDataSubstateUpOperationGroupIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("ValidatorDataSubstateUpOperationIndexInGroup")
                                .HasColumnType("integer");

                            b1.Property<decimal>("PreparedFeePercentage")
                                .HasColumnType("numeric")
                                .HasColumnName("prepared_fee_percentage");

                            b1.HasKey("ValidatorDataSubstateUpStateVersion", "ValidatorDataSubstateUpOperationGroupIndex", "ValidatorDataSubstateUpOperationIndexInGroup");

                            b1.ToTable("validator_data_substates");

                            b1.WithOwner()
                                .HasForeignKey("ValidatorDataSubstateUpStateVersion", "ValidatorDataSubstateUpOperationGroupIndex", "ValidatorDataSubstateUpOperationIndexInGroup");
                        });

                    b.OwnsOne("Common.Database.Models.Ledger.Substates.PreparedValidatorOwner", "PreparedValidatorOwner", b1 =>
                        {
                            b1.Property<long>("ValidatorDataSubstateUpStateVersion")
                                .HasColumnType("bigint");

                            b1.Property<int>("ValidatorDataSubstateUpOperationGroupIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("ValidatorDataSubstateUpOperationIndexInGroup")
                                .HasColumnType("integer");

                            b1.Property<long>("PreparedOwnerId")
                                .HasColumnType("bigint")
                                .HasColumnName("prepared_owner_id");

                            b1.HasKey("ValidatorDataSubstateUpStateVersion", "ValidatorDataSubstateUpOperationGroupIndex", "ValidatorDataSubstateUpOperationIndexInGroup");

                            b1.HasIndex("PreparedOwnerId");

                            b1.ToTable("validator_data_substates");

                            b1.HasOne("Common.Database.Models.Ledger.Normalization.Account", "PreparedOwner")
                                .WithMany()
                                .HasForeignKey("PreparedOwnerId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ValidatorDataSubstateUpStateVersion", "ValidatorDataSubstateUpOperationGroupIndex", "ValidatorDataSubstateUpOperationIndexInGroup");

                            b1.Navigation("PreparedOwner");
                        });

                    b.OwnsOne("Common.Database.Models.Ledger.Substates.PreparedValidatorRegistered", "PreparedValidatorRegistered", b1 =>
                        {
                            b1.Property<long>("ValidatorDataSubstateUpStateVersion")
                                .HasColumnType("bigint");

                            b1.Property<int>("ValidatorDataSubstateUpOperationGroupIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("ValidatorDataSubstateUpOperationIndexInGroup")
                                .HasColumnType("integer");

                            b1.Property<bool>("PreparedIsRegistered")
                                .HasColumnType("boolean")
                                .HasColumnName("prepared_is_registered");

                            b1.HasKey("ValidatorDataSubstateUpStateVersion", "ValidatorDataSubstateUpOperationGroupIndex", "ValidatorDataSubstateUpOperationIndexInGroup");

                            b1.ToTable("validator_data_substates");

                            b1.WithOwner()
                                .HasForeignKey("ValidatorDataSubstateUpStateVersion", "ValidatorDataSubstateUpOperationGroupIndex", "ValidatorDataSubstateUpOperationIndexInGroup");
                        });

                    b.OwnsOne("Common.Database.Models.Ledger.Substates.ValidatorAllowDelegation", "ValidatorAllowDelegation", b1 =>
                        {
                            b1.Property<long>("ValidatorDataSubstateUpStateVersion")
                                .HasColumnType("bigint");

                            b1.Property<int>("ValidatorDataSubstateUpOperationGroupIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("ValidatorDataSubstateUpOperationIndexInGroup")
                                .HasColumnType("integer");

                            b1.Property<bool>("AllowDelegation")
                                .HasColumnType("boolean")
                                .HasColumnName("allow_delegation");

                            b1.HasKey("ValidatorDataSubstateUpStateVersion", "ValidatorDataSubstateUpOperationGroupIndex", "ValidatorDataSubstateUpOperationIndexInGroup");

                            b1.ToTable("validator_data_substates");

                            b1.WithOwner()
                                .HasForeignKey("ValidatorDataSubstateUpStateVersion", "ValidatorDataSubstateUpOperationGroupIndex", "ValidatorDataSubstateUpOperationIndexInGroup");
                        });

                    b.OwnsOne("Common.Database.Models.Ledger.Substates.ValidatorData", "ValidatorData", b1 =>
                        {
                            b1.Property<long>("ValidatorDataSubstateUpStateVersion")
                                .HasColumnType("bigint");

                            b1.Property<int>("ValidatorDataSubstateUpOperationGroupIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("ValidatorDataSubstateUpOperationIndexInGroup")
                                .HasColumnType("integer");

                            b1.Property<decimal>("FeePercentage")
                                .HasColumnType("numeric")
                                .HasColumnName("fee_percentage");

                            b1.Property<bool>("IsRegistered")
                                .HasColumnType("boolean")
                                .HasColumnName("is_registered");

                            b1.Property<long>("OwnerId")
                                .HasColumnType("bigint")
                                .HasColumnName("owner_id");

                            b1.HasKey("ValidatorDataSubstateUpStateVersion", "ValidatorDataSubstateUpOperationGroupIndex", "ValidatorDataSubstateUpOperationIndexInGroup");

                            b1.HasIndex("OwnerId");

                            b1.ToTable("validator_data_substates");

                            b1.HasOne("Common.Database.Models.Ledger.Normalization.Account", "Owner")
                                .WithMany()
                                .HasForeignKey("OwnerId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ValidatorDataSubstateUpStateVersion", "ValidatorDataSubstateUpOperationGroupIndex", "ValidatorDataSubstateUpOperationIndexInGroup");

                            b1.Navigation("Owner");
                        });

                    b.OwnsOne("Common.Database.Models.Ledger.Substates.ValidatorMetadata", "ValidatorMetaData", b1 =>
                        {
                            b1.Property<long>("ValidatorDataSubstateUpStateVersion")
                                .HasColumnType("bigint");

                            b1.Property<int>("ValidatorDataSubstateUpOperationGroupIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("ValidatorDataSubstateUpOperationIndexInGroup")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("url");

                            b1.HasKey("ValidatorDataSubstateUpStateVersion", "ValidatorDataSubstateUpOperationGroupIndex", "ValidatorDataSubstateUpOperationIndexInGroup");

                            b1.ToTable("validator_data_substates");

                            b1.WithOwner()
                                .HasForeignKey("ValidatorDataSubstateUpStateVersion", "ValidatorDataSubstateUpOperationGroupIndex", "ValidatorDataSubstateUpOperationIndexInGroup");
                        });

                    b.Navigation("DownOperationGroup");

                    b.Navigation("PreparedValidatorFee");

                    b.Navigation("PreparedValidatorOwner");

                    b.Navigation("PreparedValidatorRegistered");

                    b.Navigation("UpOperationGroup");

                    b.Navigation("Validator");

                    b.Navigation("ValidatorAllowDelegation");

                    b.Navigation("ValidatorData");

                    b.Navigation("ValidatorMetaData");
                });

            modelBuilder.Entity("Common.Database.Models.Ledger.Substates.ValidatorStakeBalanceSubstate", b =>
                {
                    b.HasOne("Common.Database.Models.Ledger.Normalization.Validator", "Validator")
                        .WithMany()
                        .HasForeignKey("ValidatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Database.Models.Ledger.LedgerOperationGroup", "DownOperationGroup")
                        .WithMany()
                        .HasForeignKey("DownStateVersion", "DownOperationGroupIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_validator_stake_balance_substate_down_operation_group");

                    b.HasOne("Common.Database.Models.Ledger.LedgerOperationGroup", "UpOperationGroup")
                        .WithMany()
                        .HasForeignKey("UpStateVersion", "UpOperationGroupIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_validator_stake_balance_substate_up_operation_group");

                    b.Navigation("DownOperationGroup");

                    b.Navigation("UpOperationGroup");

                    b.Navigation("Validator");
                });
#pragma warning restore 612, 618
        }
    }
}
