CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TYPE account_default_deposit_rule AS ENUM ('accept', 'reject', 'allow_existing');
    CREATE TYPE account_resource_preference_rule AS ENUM ('allowed', 'disallowed');
    CREATE TYPE authorized_depositor_badge_type AS ENUM ('resource', 'non_fungible');
    CREATE TYPE entity_relationship AS ENUM ('component_to_instantiating_package', 'vault_to_resource', 'validator_to_stake_vault', 'validator_to_pending_xrd_withdraw_vault', 'validator_to_locked_owner_stake_unit_vault', 'validator_to_pending_owner_stake_unit_unlock_vault', 'stake_unit_of_validator', 'claim_token_of_validator', 'entity_to_royalty_vault', 'royalty_vault_of_entity', 'account_locker_of_locker', 'account_locker_of_account', 'resource_pool_to_unit_resource', 'resource_pool_to_resource', 'resource_pool_to_resource_vault', 'unit_resource_of_resource_pool', 'resource_vault_of_resource_pool', 'access_controller_to_recovery_badge', 'recovery_badge_of_access_controller');
    CREATE TYPE entity_type AS ENUM ('global_consensus_manager', 'global_fungible_resource', 'global_non_fungible_resource', 'global_generic_component', 'internal_generic_component', 'global_account_component', 'global_package', 'internal_key_value_store', 'internal_fungible_vault', 'internal_non_fungible_vault', 'global_validator', 'global_access_controller', 'global_identity', 'global_one_resource_pool', 'global_two_resource_pool', 'global_multi_resource_pool', 'global_transaction_tracker', 'global_account_locker');
    CREATE TYPE ledger_transaction_manifest_class AS ENUM ('general', 'transfer', 'validator_stake', 'validator_unstake', 'validator_claim', 'account_deposit_settings_update', 'pool_contribution', 'pool_redemption');
    CREATE TYPE ledger_transaction_marker_event_type AS ENUM ('withdrawal', 'deposit');
    CREATE TYPE ledger_transaction_marker_operation_type AS ENUM ('resource_in_use', 'account_deposited_into', 'account_withdrawn_from', 'account_owner_method_call', 'badge_presented');
    CREATE TYPE ledger_transaction_marker_transaction_type AS ENUM ('user', 'round_change', 'genesis_flash', 'genesis_transaction', 'protocol_update_flash', 'protocol_update_transaction');
    CREATE TYPE ledger_transaction_marker_type AS ENUM ('transaction_type', 'event', 'manifest_address', 'affected_global_entity', 'manifest_class', 'event_global_emitter', 'epoch_change');
    CREATE TYPE ledger_transaction_status AS ENUM ('succeeded', 'failed');
    CREATE TYPE ledger_transaction_type AS ENUM ('genesis', 'user', 'round_update', 'flash');
    CREATE TYPE module_id AS ENUM ('main', 'metadata', 'royalty', 'role_assignment');
    CREATE TYPE non_fungible_id_type AS ENUM ('string', 'integer', 'bytes', 'ruid');
    CREATE TYPE package_vm_type AS ENUM ('native', 'scrypto_v1');
    CREATE TYPE pending_transaction_intent_ledger_status AS ENUM ('unknown', 'committed', 'commit_pending', 'permanent_rejection', 'possible_to_commit', 'likely_but_not_certain_rejection');
    CREATE TYPE pending_transaction_payload_ledger_status AS ENUM ('unknown', 'committed', 'commit_pending', 'clashing_commit', 'permanently_rejected', 'transiently_accepted', 'transiently_rejected');
    CREATE TYPE public_key_type AS ENUM ('ecdsa_secp256k1', 'eddsa_ed25519');
    CREATE TYPE resource_type AS ENUM ('fungible', 'non_fungible');
    CREATE TYPE sbor_type_kind AS ENUM ('well_known', 'schema_local');
    CREATE TYPE standard_metadata_key AS ENUM ('dapp_account_type', 'dapp_definition', 'dapp_definitions', 'dapp_claimed_websites', 'dapp_claimed_entities', 'dapp_account_locker');
    CREATE TYPE state_type AS ENUM ('json', 'sbor');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE account_authorized_depositor_aggregate_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        account_entity_id bigint NOT NULL,
        entry_ids bigint[] NOT NULL,
        CONSTRAINT "PK_account_authorized_depositor_aggregate_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE account_authorized_depositor_entry_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        account_entity_id bigint NOT NULL,
        is_deleted boolean NOT NULL,
        discriminator authorized_depositor_badge_type NOT NULL,
        resource_entity_id bigint,
        non_fungible_id text,
        CONSTRAINT "PK_account_authorized_depositor_entry_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE account_default_deposit_rule_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        account_entity_id bigint NOT NULL,
        default_deposit_rule account_default_deposit_rule NOT NULL,
        CONSTRAINT "PK_account_default_deposit_rule_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE account_locker_entry_definition (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        account_locker_entity_id bigint NOT NULL,
        account_entity_id bigint NOT NULL,
        key_value_store_entity_id bigint NOT NULL,
        CONSTRAINT "PK_account_locker_entry_definition" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE account_locker_entry_resource_vault_definition (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        account_locker_definition_id bigint NOT NULL,
        resource_entity_id bigint NOT NULL,
        vault_entity_id bigint NOT NULL,
        CONSTRAINT "PK_account_locker_entry_resource_vault_definition" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE account_locker_entry_touch_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        account_locker_definition_id bigint NOT NULL,
        CONSTRAINT "PK_account_locker_entry_touch_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE account_resource_preference_rule_aggregate_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        account_entity_id bigint NOT NULL,
        entry_ids bigint[] NOT NULL,
        CONSTRAINT "PK_account_resource_preference_rule_aggregate_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE account_resource_preference_rule_entry_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        account_entity_id bigint NOT NULL,
        resource_entity_id bigint NOT NULL,
        account_resource_preference_rule account_resource_preference_rule,
        is_deleted boolean NOT NULL,
        CONSTRAINT "PK_account_resource_preference_rule_entry_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE component_method_royalty_aggregate_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        entry_ids bigint[] NOT NULL,
        CONSTRAINT "PK_component_method_royalty_aggregate_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE component_method_royalty_entry_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        method_name text NOT NULL,
        royalty_amount jsonb,
        is_locked boolean NOT NULL,
        CONSTRAINT "PK_component_method_royalty_entry_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE entities (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        address text NOT NULL,
        is_global boolean NOT NULL,
        ancestor_ids bigint[],
        parent_ancestor_id bigint,
        owner_ancestor_id bigint,
        global_ancestor_id bigint,
        correlated_entity_relationships entity_relationship[] NOT NULL,
        correlated_entity_ids bigint[] NOT NULL,
        discriminator entity_type NOT NULL,
        blueprint_name text,
        blueprint_version text,
        assigned_module_ids module_id[],
        divisibility integer,
        non_fungible_id_type non_fungible_id_type,
        non_fungible_data_mutable_fields text[],
        CONSTRAINT "PK_entities" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE entity_metadata_entry_definition (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        key text NOT NULL,
        CONSTRAINT "PK_entity_metadata_entry_definition" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE entity_metadata_entry_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_metadata_entry_definition_id bigint NOT NULL,
        value bytea,
        is_deleted boolean NOT NULL,
        is_locked boolean NOT NULL,
        CONSTRAINT "PK_entity_metadata_entry_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE entity_metadata_totals_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        total_entries_including_deleted bigint NOT NULL,
        total_entries_excluding_deleted bigint NOT NULL,
        CONSTRAINT "PK_entity_metadata_totals_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE entity_resource_balance_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        resource_entity_id bigint NOT NULL,
        balance numeric(1000) NOT NULL,
        CONSTRAINT "PK_entity_resource_balance_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE entity_resource_entry_definition (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        resource_entity_id bigint NOT NULL,
        resource_type resource_type NOT NULL,
        CONSTRAINT "PK_entity_resource_entry_definition" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE entity_resource_totals_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        total_count bigint NOT NULL,
        total_fungible_count bigint NOT NULL,
        total_non_fungible_count bigint NOT NULL,
        CONSTRAINT "PK_entity_resource_totals_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE entity_resource_vault_entry_definition (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        resource_entity_id bigint NOT NULL,
        vault_entity_id bigint NOT NULL,
        CONSTRAINT "PK_entity_resource_vault_entry_definition" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE entity_resource_vault_totals_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        resource_entity_id bigint NOT NULL,
        total_count bigint NOT NULL,
        CONSTRAINT "PK_entity_resource_vault_totals_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE entity_role_assignments_aggregate_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        owner_role_id bigint NOT NULL,
        entry_ids bigint[] NOT NULL,
        CONSTRAINT "PK_entity_role_assignments_aggregate_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE entity_role_assignments_entry_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        key_role text NOT NULL,
        key_module module_id NOT NULL,
        role_assignments jsonb,
        is_deleted boolean NOT NULL,
        CONSTRAINT "PK_entity_role_assignments_entry_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE entity_role_assignments_owner_role_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        role_assignments jsonb NOT NULL,
        CONSTRAINT "PK_entity_role_assignments_owner_role_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE key_value_store_entry_definition (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        key_value_store_entity_id bigint NOT NULL,
        key bytea NOT NULL,
        CONSTRAINT "PK_key_value_store_entry_definition" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE key_value_store_entry_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        key_value_store_entry_definition_id bigint NOT NULL,
        value bytea,
        is_deleted boolean NOT NULL,
        is_locked boolean NOT NULL,
        CONSTRAINT "PK_key_value_store_entry_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE key_value_store_schema_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        key_value_store_entity_id bigint NOT NULL,
        key_schema_hash bytea NOT NULL,
        key_schema_defining_entity_id bigint NOT NULL,
        key_sbor_type_kind sbor_type_kind NOT NULL,
        key_type_index bigint NOT NULL,
        value_schema_hash bytea NOT NULL,
        value_schema_defining_entity_id bigint NOT NULL,
        value_sbor_type_kind sbor_type_kind NOT NULL,
        value_type_index bigint NOT NULL,
        CONSTRAINT "PK_key_value_store_schema_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE key_value_store_totals_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        total_entries_including_deleted bigint NOT NULL,
        total_entries_excluding_deleted bigint NOT NULL,
        CONSTRAINT "PK_key_value_store_totals_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE ledger_transaction_events (
        state_version bigint NOT NULL,
        receipt_event_emitters jsonb[] NOT NULL,
        receipt_event_names text[] NOT NULL,
        receipt_event_sbors bytea[] NOT NULL,
        receipt_event_schema_entity_ids bigint[] NOT NULL,
        receipt_event_schema_hashes bytea[] NOT NULL,
        receipt_event_type_indexes bigint[] NOT NULL,
        receipt_event_sbor_type_kinds sbor_type_kind[] NOT NULL,
        CONSTRAINT "PK_ledger_transaction_events" PRIMARY KEY (state_version)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE ledger_transaction_markers (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        state_version bigint NOT NULL,
        discriminator ledger_transaction_marker_type NOT NULL,
        entity_id bigint,
        epoch_change boolean,
        event_type ledger_transaction_marker_event_type,
        resource_entity_id bigint,
        quantity numeric(1000),
        operation_type ledger_transaction_marker_operation_type,
        manifest_class ledger_transaction_manifest_class,
        is_most_specific boolean,
        transaction_type ledger_transaction_marker_transaction_type,
        CONSTRAINT "PK_ledger_transaction_markers" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE ledger_transactions (
        state_version bigint NOT NULL,
        epoch bigint NOT NULL,
        round_in_epoch bigint NOT NULL,
        index_in_epoch bigint NOT NULL,
        index_in_round bigint NOT NULL,
        fee_paid numeric(1000) NOT NULL,
        tip_paid numeric(1000) NOT NULL,
        affected_global_entities bigint[] NOT NULL,
        round_timestamp timestamp with time zone NOT NULL,
        created_timestamp timestamp with time zone NOT NULL,
        normalized_round_timestamp timestamp with time zone NOT NULL,
        receipt_status ledger_transaction_status NOT NULL,
        receipt_fee_summary jsonb NOT NULL,
        receipt_state_updates jsonb,
        receipt_costing_parameters jsonb NOT NULL,
        receipt_fee_source jsonb,
        receipt_fee_destination jsonb,
        receipt_next_epoch jsonb,
        receipt_output jsonb,
        receipt_error_message text,
        balance_changes jsonb,
        transaction_tree_hash text NOT NULL,
        receipt_tree_hash text NOT NULL,
        state_tree_hash text NOT NULL,
        discriminator ledger_transaction_type NOT NULL,
        payload_hash text,
        intent_hash text,
        signed_intent_hash text,
        message jsonb,
        raw_payload bytea,
        manifest_instructions text,
        manifest_classes ledger_transaction_manifest_class[],
        CONSTRAINT "PK_ledger_transactions" PRIMARY KEY (state_version)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE non_fungible_id_data_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        non_fungible_id_definition_id bigint NOT NULL,
        data bytea,
        is_deleted boolean NOT NULL,
        is_locked boolean NOT NULL,
        CONSTRAINT "PK_non_fungible_id_data_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE non_fungible_id_definition (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        non_fungible_resource_entity_id bigint NOT NULL,
        non_fungible_id text NOT NULL,
        CONSTRAINT "PK_non_fungible_id_definition" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE non_fungible_id_location_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        non_fungible_id_definition_id bigint NOT NULL,
        vault_entity_id bigint NOT NULL,
        CONSTRAINT "PK_non_fungible_id_location_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE non_fungible_schema_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        resource_entity_id bigint NOT NULL,
        schema_defining_entity_id bigint NOT NULL,
        schema_hash bytea NOT NULL,
        sbor_type_kind sbor_type_kind NOT NULL,
        type_index bigint NOT NULL,
        CONSTRAINT "PK_non_fungible_schema_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE non_fungible_vault_entry_definition (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        vault_entity_id bigint NOT NULL,
        non_fungible_id_definition_id bigint NOT NULL,
        CONSTRAINT "PK_non_fungible_vault_entry_definition" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE non_fungible_vault_entry_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        non_fungible_vault_entry_definition_id bigint NOT NULL,
        is_deleted boolean NOT NULL,
        CONSTRAINT "PK_non_fungible_vault_entry_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE package_blueprint_aggregate_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        package_entity_id bigint NOT NULL,
        package_blueprint_ids bigint[] NOT NULL,
        CONSTRAINT "PK_package_blueprint_aggregate_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE package_blueprint_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        package_entity_id bigint NOT NULL,
        name text NOT NULL,
        version text NOT NULL,
        definition jsonb NOT NULL,
        dependant_entity_ids bigint[],
        auth_template jsonb,
        auth_template_is_locked boolean,
        royalty_config jsonb,
        royalty_config_is_locked boolean,
        CONSTRAINT "PK_package_blueprint_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE package_code_aggregate_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        package_entity_id bigint NOT NULL,
        package_code_ids bigint[] NOT NULL,
        CONSTRAINT "PK_package_code_aggregate_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE package_code_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        package_entity_id bigint NOT NULL,
        code_hash bytea NOT NULL,
        code bytea NOT NULL,
        vm_type package_vm_type NOT NULL,
        is_deleted boolean NOT NULL,
        CONSTRAINT "PK_package_code_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE pending_transactions (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        payload_hash text NOT NULL,
        intent_hash text NOT NULL,
        end_epoch_exclusive bigint NOT NULL,
        payload_id bigint,
        payload_status pending_transaction_payload_ledger_status NOT NULL,
        intent_status pending_transaction_intent_ledger_status NOT NULL,
        initial_rejection_reason text,
        latest_rejection_reason text,
        latest_rejection_timestamp timestamp with time zone,
        commit_timestamp timestamp with time zone,
        resubmit_from_timestamp timestamp with time zone,
        handling_status_reason text,
        first_submitted_to_gateway_timestamp timestamp with time zone NOT NULL,
        node_submission_count integer NOT NULL,
        latest_node_submission_timestamp timestamp with time zone,
        latest_submitted_to_node_name text,
        latest_node_submission_was_accepted boolean NOT NULL,
        last_submit_error text,
        CONSTRAINT "PK_pending_transactions" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE resource_entity_supply_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        resource_entity_id bigint NOT NULL,
        total_supply numeric(1000) NOT NULL,
        total_minted numeric(1000) NOT NULL,
        total_burned numeric(1000) NOT NULL,
        CONSTRAINT "PK_resource_entity_supply_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE resource_holders (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        entity_id bigint NOT NULL,
        resource_entity_id bigint NOT NULL,
        balance numeric(1000) NOT NULL,
        last_updated_at_state_version bigint NOT NULL,
        CONSTRAINT "PK_resource_holders" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE schema_entry_aggregate_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        entry_ids bigint[] NOT NULL,
        CONSTRAINT "PK_schema_entry_aggregate_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE schema_entry_definition (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        schema_hash bytea NOT NULL,
        schema bytea NOT NULL,
        CONSTRAINT "PK_schema_entry_definition" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE state_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        discriminator state_type NOT NULL,
        json_state jsonb,
        sbor_state bytea,
        schema_hash bytea,
        sbor_type_kind sbor_type_kind,
        type_index bigint,
        schema_defining_entity_id bigint,
        CONSTRAINT "PK_state_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE unverified_standard_metadata_aggregate_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        entry_ids bigint[] NOT NULL,
        CONSTRAINT "PK_unverified_standard_metadata_aggregate_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE unverified_standard_metadata_entry_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        entity_id bigint NOT NULL,
        is_deleted boolean NOT NULL,
        is_locked boolean NOT NULL,
        discriminator standard_metadata_key NOT NULL,
        entity_ids bigint[],
        values text[],
        CONSTRAINT "PK_unverified_standard_metadata_entry_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE validator_cumulative_emission_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        validator_entity_id bigint NOT NULL,
        epoch_number bigint NOT NULL,
        proposals_made bigint NOT NULL,
        proposals_missed bigint NOT NULL,
        participation_in_active_set bigint NOT NULL,
        CONSTRAINT "PK_validator_cumulative_emission_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE validator_public_key_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        validator_entity_id bigint NOT NULL,
        key_type public_key_type NOT NULL,
        key bytea NOT NULL,
        CONSTRAINT "PK_validator_public_key_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE vault_balance_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        vault_entity_id bigint NOT NULL,
        balance numeric(1000) NOT NULL,
        CONSTRAINT "PK_vault_balance_history" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE pending_transaction_payloads (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        pending_transaction_id bigint,
        notarized_transaction_blob bytea NOT NULL,
        CONSTRAINT "PK_pending_transaction_payloads" PRIMARY KEY (id),
        CONSTRAINT "FK_pending_transaction_payloads_pending_transactions_pending_t~" FOREIGN KEY (pending_transaction_id) REFERENCES pending_transactions (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE TABLE validator_active_set_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        from_state_version bigint NOT NULL,
        epoch bigint NOT NULL,
        validator_public_key_history_id bigint NOT NULL,
        stake numeric(1000) NOT NULL,
        CONSTRAINT "PK_validator_active_set_history" PRIMARY KEY (id),
        CONSTRAINT "FK_validator_active_set_history_validator_public_key_history_v~" FOREIGN KEY (validator_public_key_history_id) REFERENCES validator_public_key_history (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_account_authorized_depositor_aggregate_history_account_enti~" ON account_authorized_depositor_aggregate_history (account_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_account_authorized_depositor_entry_history_account_entity_~1" ON account_authorized_depositor_entry_history (account_entity_id, resource_entity_id, non_fungible_id, from_state_version) WHERE discriminator = 'non_fungible';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_account_authorized_depositor_entry_history_account_entity_~2" ON account_authorized_depositor_entry_history (account_entity_id, resource_entity_id, from_state_version) WHERE discriminator = 'resource';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_account_authorized_depositor_entry_history_account_entity_i~" ON account_authorized_depositor_entry_history (account_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_account_default_deposit_rule_history_account_entity_id_from~" ON account_default_deposit_rule_history (account_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_account_locker_entry_definition_account_locker_entity_id_ac~" ON account_locker_entry_definition (account_locker_entity_id, account_entity_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_account_locker_entry_resource_vault_definition_account_lock~" ON account_locker_entry_resource_vault_definition (account_locker_definition_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_account_locker_entry_touch_history_account_locker_definitio~" ON account_locker_entry_touch_history (account_locker_definition_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_account_resource_preference_rule_aggregate_history_account_~" ON account_resource_preference_rule_aggregate_history (account_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_account_resource_preference_rule_entry_history_account_enti~" ON account_resource_preference_rule_entry_history (account_entity_id, resource_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_component_method_royalty_aggregate_history_entity_id_from_s~" ON component_method_royalty_aggregate_history (entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_component_method_royalty_entry_history_entity_id_from_state~" ON component_method_royalty_entry_history (entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_component_method_royalty_entry_history_entity_id_method_nam~" ON component_method_royalty_entry_history (entity_id, method_name, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_entities_address" ON entities (address);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entities_from_state_version" ON entities (from_state_version) WHERE discriminator = 'global_validator';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_metadata_entry_definition_entity_id_from_state_versi~" ON entity_metadata_entry_definition (entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_metadata_entry_definition_entity_id_key" ON entity_metadata_entry_definition (entity_id, key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_metadata_entry_history_entity_metadata_entry_definit~" ON entity_metadata_entry_history (entity_metadata_entry_definition_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_metadata_totals_history_entity_id_from_state_version" ON entity_metadata_totals_history (entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_resource_balance_history_entity_id_resource_entity_i~" ON entity_resource_balance_history (entity_id, resource_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_resource_entry_definition_entity_id_from_state_versi~" ON entity_resource_entry_definition (entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_resource_entry_definition_fungibles" ON entity_resource_entry_definition (entity_id, from_state_version) WHERE resource_type = 'fungible';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_resource_entry_definition_non_fungibles" ON entity_resource_entry_definition (entity_id, from_state_version) WHERE resource_type = 'non_fungible';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_resource_totals_history_entity_id_from_state_version" ON entity_resource_totals_history (entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_resource_vault_entry_definition_entity_id_resource_e~" ON entity_resource_vault_entry_definition (entity_id, resource_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_resource_vault_totals_history_entity_id_resource_ent~" ON entity_resource_vault_totals_history (entity_id, resource_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_role_assignments_aggregate_history_entity_id_from_st~" ON entity_role_assignments_aggregate_history (entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_role_assignments_entry_history_entity_id_key_role_ke~" ON entity_role_assignments_entry_history (entity_id, key_role, key_module, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_entity_role_assignments_owner_role_history_entity_id_from_s~" ON entity_role_assignments_owner_role_history (entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_key_value_store_entry_definition_key_value_store_entity_id_~" ON key_value_store_entry_definition (key_value_store_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_key_value_store_entry_definition_key_value_store_entity_id~1" ON key_value_store_entry_definition (key_value_store_entity_id, key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_key_value_store_entry_history_key_value_store_entry_definit~" ON key_value_store_entry_history (key_value_store_entry_definition_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_key_value_store_schema_history_key_value_store_entity_id_fr~" ON key_value_store_schema_history (key_value_store_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_key_value_store_totals_history_entity_id_from_state_version" ON key_value_store_totals_history (entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_ledger_transaction_markers_entity_id_state_version" ON ledger_transaction_markers (entity_id, state_version) WHERE discriminator = 'event_global_emitter';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_ledger_transaction_markers_entity_id_state_version1" ON ledger_transaction_markers (entity_id, state_version) WHERE discriminator = 'affected_global_entity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_ledger_transaction_markers_epoch_change_state_version" ON ledger_transaction_markers (epoch_change, state_version) WHERE discriminator = 'epoch_change';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_ledger_transaction_markers_event_type_entity_id_state_versi~" ON ledger_transaction_markers (event_type, entity_id, state_version) WHERE discriminator = 'event';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_ledger_transaction_markers_manifest_class" ON ledger_transaction_markers (manifest_class, state_version) WHERE discriminator = 'manifest_class';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_ledger_transaction_markers_manifest_class_is_most_specific" ON ledger_transaction_markers (manifest_class, state_version) WHERE discriminator = 'manifest_class' and is_most_specific = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_ledger_transaction_markers_operation_type_entity_id_state_v~" ON ledger_transaction_markers (operation_type, entity_id, state_version) WHERE discriminator = 'manifest_address';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_ledger_transaction_markers_state_version" ON ledger_transaction_markers (state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_ledger_transaction_markers_transaction_type_state_version" ON ledger_transaction_markers (transaction_type, state_version) WHERE discriminator = 'transaction_type';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ledger_transactions_epoch_round_in_epoch" ON ledger_transactions (epoch, round_in_epoch) WHERE index_in_round = 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_ledger_transactions_intent_hash" ON ledger_transactions USING hash (intent_hash) WHERE intent_hash IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_ledger_transactions_round_timestamp" ON ledger_transactions (round_timestamp);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_non_fungible_id_data_history_non_fungible_id_definition_id_~" ON non_fungible_id_data_history (non_fungible_id_definition_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_non_fungible_id_definition_non_fungible_resource_entity_id_~" ON non_fungible_id_definition (non_fungible_resource_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_non_fungible_id_definition_non_fungible_resource_entity_id~1" ON non_fungible_id_definition (non_fungible_resource_entity_id, non_fungible_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_non_fungible_id_location_history_non_fungible_id_definition~" ON non_fungible_id_location_history (non_fungible_id_definition_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_non_fungible_schema_history_resource_entity_id_from_state_v~" ON non_fungible_schema_history (resource_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_non_fungible_vault_entry_definition_vault_entity_id_from_st~" ON non_fungible_vault_entry_definition (vault_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_non_fungible_vault_entry_history_non_fungible_vault_entry_d~" ON non_fungible_vault_entry_history (non_fungible_vault_entry_definition_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_package_blueprint_aggregate_history_package_entity_id_from_~" ON package_blueprint_aggregate_history (package_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_package_blueprint_history_package_entity_id_from_state_vers~" ON package_blueprint_history (package_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_package_blueprint_history_package_entity_id_name_version_fr~" ON package_blueprint_history (package_entity_id, name, version, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_package_code_aggregate_history_package_entity_id_from_state~" ON package_code_aggregate_history (package_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_package_code_history_package_entity_id_from_state_version" ON package_code_history (package_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_pending_transaction_payloads_pending_transaction_id" ON pending_transaction_payloads (pending_transaction_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_pending_transactions_first_submitted_to_gateway_timestamp" ON pending_transactions (first_submitted_to_gateway_timestamp);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_pending_transactions_intent_hash" ON pending_transactions (intent_hash);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_pending_transactions_payload_hash" ON pending_transactions (payload_hash);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_pending_transactions_resubmit_from_timestamp" ON pending_transactions (resubmit_from_timestamp);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_resource_entity_supply_history_resource_entity_id_from_stat~" ON resource_entity_supply_history (resource_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_resource_holders_entity_id_resource_entity_id" ON resource_holders (entity_id, resource_entity_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_resource_holders_entity_id_resource_entity_id_balance" ON resource_holders (entity_id, resource_entity_id, balance);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_schema_entry_aggregate_history_entity_id_from_state_version" ON schema_entry_aggregate_history (entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_schema_entry_definition_entity_id_schema_hash" ON schema_entry_definition (entity_id, schema_hash);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_state_history_entity_id_from_state_version" ON state_history (entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_unverified_standard_metadata_aggregate_history_entity_id_fr~" ON unverified_standard_metadata_aggregate_history (entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_unverified_standard_metadata_entry_history_entity_id_discri~" ON unverified_standard_metadata_entry_history (entity_id, discriminator, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_validator_active_set_history_epoch" ON validator_active_set_history (epoch);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_validator_active_set_history_from_state_version" ON validator_active_set_history (from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_validator_active_set_history_validator_public_key_history_id" ON validator_active_set_history (validator_public_key_history_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_validator_cumulative_emission_history_validator_entity_id_e~" ON validator_cumulative_emission_history (validator_entity_id, epoch_number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_validator_cumulative_emission_history_validator_entity_id_f~" ON validator_cumulative_emission_history (validator_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_validator_public_key_history_validator_entity_id_from_state~" ON validator_public_key_history (validator_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_validator_public_key_history_validator_entity_id_key_type_k~" ON validator_public_key_history (validator_entity_id, key_type, key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    CREATE INDEX "IX_vault_balance_history_vault_entity_id_from_state_version" ON vault_balance_history (vault_entity_id, from_state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241016083503_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241016083503_InitialCreate', '8.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241111165721_AddUserLedgerTransactionV2Support') THEN
    ALTER TYPE ledger_transaction_type ADD VALUE 'user_v2' BEFORE 'round_update';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241111165721_AddUserLedgerTransactionV2Support') THEN
    CREATE TABLE ledger_finalized_subintents (
        subintent_hash character varying(90) NOT NULL,
        finalized_at_state_version bigint NOT NULL,
        finalized_at_transaction_intent_hash character varying(90) NOT NULL,
        CONSTRAINT "PK_ledger_finalized_subintents" PRIMARY KEY (subintent_hash)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241111165721_AddUserLedgerTransactionV2Support') THEN
    CREATE TABLE ledger_transaction_subintent_data (
        state_version bigint NOT NULL,
        child_subintent_hashes text[] NOT NULL,
        subintent_data jsonb NOT NULL,
        CONSTRAINT "PK_ledger_transaction_subintent_data" PRIMARY KEY (state_version)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241111165721_AddUserLedgerTransactionV2Support') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241111165721_AddUserLedgerTransactionV2Support', '8.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211105351_NewResourceBalanceChangeTransactionMarker') THEN
    ALTER TYPE ledger_transaction_marker_type ADD VALUE 'resource_balance_change';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211105351_NewResourceBalanceChangeTransactionMarker') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241211105351_NewResourceBalanceChangeTransactionMarker', '8.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211111619_RemoveRoundUpdateTransactionMarkers') THEN
    DELETE FROM ledger_transaction_markers WHERE transaction_type = 'round_change';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211111619_RemoveRoundUpdateTransactionMarkers') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241211111619_RemoveRoundUpdateTransactionMarkers', '8.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241217093304_AddLedgerTransactionStatusIndex') THEN
    CREATE INDEX "IX_ledger_transactions_receipt_status" ON ledger_transactions (receipt_status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241217093304_AddLedgerTransactionStatusIndex') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241217093304_AddLedgerTransactionStatusIndex', '8.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250109081643_AddTransactionResourceBalanceChangeIndex') THEN
    DROP INDEX "IX_ledger_transactions_receipt_status";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250109081643_AddTransactionResourceBalanceChangeIndex') THEN
    CREATE INDEX "IX_ledger_transactions_receipt_status_state_version" ON ledger_transactions (receipt_status, state_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250109081643_AddTransactionResourceBalanceChangeIndex') THEN
    CREATE INDEX "IX_ledger_transaction_markers_resource_balance_change" ON ledger_transaction_markers (entity_id, state_version) WHERE discriminator = 'resource_balance_change';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250109081643_AddTransactionResourceBalanceChangeIndex') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250109081643_AddTransactionResourceBalanceChangeIndex', '8.0.2');
    END IF;
END $EF$;
COMMIT;

