/* Copyright 2021 Radix Publishing Ltd incorporated in Jersey (Channel Islands).
 *
 * Licensed under the Radix License, Version 1.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the License at:
 *
 * radixfoundation.org/licenses/LICENSE-v1
 *
 * The Licensor hereby grants permission for the Canonical version of the Work to be
 * published, distributed and used under or by reference to the Licensor’s trademark
 * Radix ® and use of any unregistered trade names, logos or get-up.
 *
 * The Licensor provides the Work (and each Contributor provides its Contributions) on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied,
 * including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT,
 * MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * Whilst the Work is capable of being deployed, used and adopted (instantiated) to create
 * a distributed ledger it is your responsibility to test and validate the code, together
 * with all logic and performance of that code under all foreseeable scenarios.
 *
 * The Licensor does not make or purport to make and hereby excludes liability for all
 * and any representation, warranty or undertaking in any form whatsoever, whether express
 * or implied, to any entity or person, including any representation, warranty or
 * undertaking, as to the functionality security use, value or other characteristics of
 * any distributed ledger nor in respect the functioning or value of any tokens which may
 * be created stored or transferred using the Work. The Licensor does not warrant that the
 * Work or any use of the Work complies with any law or regulation in any territory where
 * it may be implemented or used or that it will be appropriate for any specific purpose.
 *
 * Neither the licensor nor any current or former employees, officers, directors, partners,
 * trustees, representatives, agents, advisors, contractors, or volunteers of the Licensor
 * shall be liable for any direct or indirect, special, incidental, consequential or other
 * losses of any kind, in tort, contract or otherwise (including but not limited to loss
 * of revenue, income or profits, or loss of use or data, or loss of reputation, or loss
 * of any economic or other opportunity of whatsoever nature or howsoever arising), arising
 * out of or in connection with (without limitation of any use, misuse, of any ledger system
 * or use made or its functionality or any performance or operation of any code or protocol
 * caused by bugs or programming or logic errors or otherwise);
 *
 * A. any offer, purchase, holding, use, sale, exchange or transmission of any
 * cryptographic keys, tokens or assets created, exchanged, stored or arising from any
 * interaction with the Work;
 *
 * B. any failure in a transmission or loss of any token or assets keys or other digital
 * artefacts due to errors in transmission;
 *
 * C. bugs, hacks, logic errors or faults in the Work or any communication;
 *
 * D. system software or apparatus including but not limited to losses caused by errors
 * in holding or transmitting tokens by any third-party;
 *
 * E. breaches or failure of security including hacker attacks, loss or disclosure of
 * password, loss of private key, unauthorised use or misuse of such passwords or keys;
 *
 * F. any losses including loss of anticipated savings or other benefits resulting from
 * use of the Work or any changes to the Work (however implemented).
 *
 * You are solely responsible for; testing, validating and evaluation of all operation
 * logic, functionality, security and appropriateness of using the Work for any commercial
 * or non-commercial purpose and for any reproduction or redistribution by You of the
 * Work. You assume all risks associated with Your use of the Work and the exercise of
 * permissions under this License.
 */

// <auto-generated />
using System;
using System.Collections.Generic;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RadixDlt.NetworkGateway.Abstractions.Addressing;
using RadixDlt.NetworkGateway.Abstractions.Model;
using RadixDlt.NetworkGateway.PostgresIntegration;
using RadixDlt.NetworkGateway.PostgresIntegration.Models;

#nullable disable

namespace RadixDlt.NetworkGateway.PostgresIntegration.Migrations
{
    [DbContext(typeof(MigrationsDbContext))]
    partial class MigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "account_default_deposit_rule", new[] { "accept", "reject", "allow_existing" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "account_resource_preference_rule", new[] { "allowed", "disallowed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "entity_type", new[] { "global_consensus_manager", "global_fungible_resource", "global_non_fungible_resource", "global_generic_component", "internal_generic_component", "global_account_component", "global_package", "internal_key_value_store", "internal_fungible_vault", "internal_non_fungible_vault", "global_validator", "global_access_controller", "global_identity", "global_one_resource_pool", "global_two_resource_pool", "global_multi_resource_pool", "global_transaction_tracker" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ledger_transaction_marker_event_type", new[] { "withdrawal", "deposit" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ledger_transaction_marker_operation_type", new[] { "resource_in_use", "account_deposited_into", "account_withdrawn_from" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ledger_transaction_marker_origin_type", new[] { "user", "epoch_change" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ledger_transaction_marker_type", new[] { "origin", "event", "manifest_address", "affected_global_entity" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ledger_transaction_status", new[] { "succeeded", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ledger_transaction_type", new[] { "genesis", "user", "round_update" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "module_id", new[] { "main", "metadata", "royalty", "role_assignment" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "non_fungible_id_type", new[] { "string", "integer", "bytes", "ruid" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "package_vm_type", new[] { "native", "scrypto_v1" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pending_transaction_status", new[] { "submitted_or_known_in_node_mempool", "missing", "rejected_temporarily", "rejected_permanently", "committed_success", "committed_failure" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public_key_type", new[] { "ecdsa_secp256k1", "eddsa_ed25519" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "resource_type", new[] { "fungible", "non_fungible" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "sbor_type_kind", new[] { "well_known", "schema_local" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "state_type", new[] { "json", "sbor" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.AccountDefaultDepositRuleHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_entity_id");

                    b.Property<AccountDefaultDepositRule>("DefaultDepositRule")
                        .HasColumnType("account_default_deposit_rule")
                        .HasColumnName("default_deposit_rule");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.HasKey("Id");

                    b.HasIndex("AccountEntityId", "FromStateVersion");

                    b.ToTable("account_default_deposit_rule_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.AccountResourcePreferenceRuleHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_entity_id");

                    b.Property<AccountResourcePreferenceRule?>("AccountResourcePreferenceRule")
                        .HasColumnType("account_resource_preference_rule")
                        .HasColumnName("account_resource_preference_rule");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("ResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountEntityId", "ResourceEntityId", "FromStateVersion");

                    b.ToTable("account_resource_preference_rule_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ComponentMethodRoyaltyEntryHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method_name");

                    b.Property<string>("RoyaltyAmount")
                        .HasColumnType("jsonb")
                        .HasColumnName("royalty_amount");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "FromStateVersion");

                    b.HasIndex("EntityId", "MethodName", "FromStateVersion");

                    b.ToTable("component_method_royalty_entry_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<List<long>>("AncestorIds")
                        .HasColumnType("bigint[]")
                        .HasColumnName("ancestor_ids");

                    b.Property<List<long>>("CorrelatedEntities")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("correlated_entities");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long?>("GlobalAncestorId")
                        .HasColumnType("bigint")
                        .HasColumnName("global_ancestor_id");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global");

                    b.Property<long?>("OwnerAncestorId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_ancestor_id");

                    b.Property<long?>("ParentAncestorId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_ancestor_id");

                    b.Property<EntityType>("discriminator")
                        .HasColumnType("entity_type");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("FromStateVersion")
                        .HasFilter("discriminator = 'global_validator'");

                    b.ToTable("entities");

                    b.HasDiscriminator<EntityType>("discriminator");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityMetadataAggregateHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<List<long>>("MetadataIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("metadata_ids");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "FromStateVersion");

                    b.ToTable("entity_metadata_aggregate_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityMetadataHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<byte[]>("Value")
                        .HasColumnType("bytea")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Key", "FromStateVersion");

                    b.ToTable("entity_metadata_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityResourceAggregateHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<List<long>>("FungibleResourceEntityIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("fungible_resource_entity_ids");

                    b.Property<List<long>>("FungibleResourceSignificantUpdateStateVersions")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("fungible_resource_significant_update_state_versions");

                    b.Property<List<long>>("NonFungibleResourceEntityIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("non_fungible_resource_entity_ids");

                    b.Property<List<long>>("NonFungibleResourceSignificantUpdateStateVersions")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("non_fungible_resource_significant_update_state_versions");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "FromStateVersion");

                    b.ToTable("entity_resource_aggregate_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityResourceAggregatedVaultsHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("ResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.Property<ResourceType>("discriminator")
                        .HasColumnType("resource_type");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "ResourceEntityId", "FromStateVersion");

                    b.ToTable("entity_resource_aggregated_vaults_history");

                    b.HasDiscriminator<ResourceType>("discriminator");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityResourceVaultAggregateHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("ResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.Property<List<long>>("VaultEntityIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("vault_entity_ids");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "ResourceEntityId", "FromStateVersion");

                    b.ToTable("entity_resource_vault_aggregate_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityRoleAssignmentsAggregateHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<List<long>>("EntryIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("entry_ids");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("OwnerRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_role_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "FromStateVersion");

                    b.ToTable("entity_role_assignments_aggregate_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityRoleAssignmentsEntryHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<ModuleId>("KeyModule")
                        .HasColumnType("module_id")
                        .HasColumnName("key_module");

                    b.Property<string>("KeyRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_role");

                    b.Property<string>("RoleAssignments")
                        .HasColumnType("jsonb")
                        .HasColumnName("role_assignments");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "KeyRole", "KeyModule", "FromStateVersion");

                    b.ToTable("entity_role_assignments_entry_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityRoleAssignmentsOwnerRoleHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<string>("RoleAssignments")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("role_assignments");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "FromStateVersion");

                    b.ToTable("entity_role_assignments_owner_role_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityVaultHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("GlobalEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("global_entity_id");

                    b.Property<long>("OwnerEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_entity_id");

                    b.Property<long>("ResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.Property<long>("VaultEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("vault_entity_id");

                    b.Property<ResourceType>("discriminator")
                        .HasColumnType("resource_type");

                    b.HasKey("Id");

                    b.HasIndex("GlobalEntityId", "FromStateVersion")
                        .HasFilter("is_royalty_vault = true");

                    b.HasIndex("OwnerEntityId", "FromStateVersion")
                        .HasFilter("is_royalty_vault = true");

                    b.HasIndex("VaultEntityId", "FromStateVersion")
                        .HasFilter("discriminator = 'non_fungible'");

                    b.HasIndex("GlobalEntityId", "VaultEntityId", "FromStateVersion");

                    b.HasIndex("Id", "ResourceEntityId", "FromStateVersion");

                    b.HasIndex("OwnerEntityId", "VaultEntityId", "FromStateVersion");

                    b.ToTable("entity_vault_history");

                    b.HasDiscriminator<ResourceType>("discriminator");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.KeyValueStoreEntryHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key");

                    b.Property<long>("KeyValueStoreEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("key_value_store_entity_id");

                    b.Property<byte[]>("Value")
                        .HasColumnType("bytea")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("KeyValueStoreEntityId", "Key", "FromStateVersion");

                    b.ToTable("key_value_store_entry_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.KeyValueStoreSchemaHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<SborTypeKind>("KeySborTypeKind")
                        .HasColumnType("sbor_type_kind")
                        .HasColumnName("key_sbor_type_kind");

                    b.Property<long>("KeySchemaDefiningEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("key_schema_defining_entity_id");

                    b.Property<byte[]>("KeySchemaHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_schema_hash");

                    b.Property<long>("KeyTypeIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("key_type_index");

                    b.Property<long>("KeyValueStoreEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("key_value_store_entity_id");

                    b.Property<SborTypeKind>("ValueSborTypeKind")
                        .HasColumnType("sbor_type_kind")
                        .HasColumnName("value_sbor_type_kind");

                    b.Property<long>("ValueSchemaDefiningEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("value_schema_defining_entity_id");

                    b.Property<byte[]>("ValueSchemaHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("value_schema_hash");

                    b.Property<long>("ValueTypeIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("value_type_index");

                    b.HasKey("Id");

                    b.HasIndex("KeyValueStoreEntityId", "FromStateVersion");

                    b.ToTable("key_value_store_schema_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransaction", b =>
                {
                    b.Property<long>("StateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("state_version");

                    b.Property<long[]>("AffectedGlobalEntities")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("affected_global_entities");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint")
                        .HasColumnName("epoch");

                    b.Property<BigInteger>("FeePaid")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("fee_paid");

                    b.Property<long>("IndexInEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("index_in_epoch");

                    b.Property<long>("IndexInRound")
                        .HasColumnType("bigint")
                        .HasColumnName("index_in_round");

                    b.Property<DateTime>("NormalizedRoundTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("normalized_round_timestamp");

                    b.Property<long>("RoundInEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("round_in_epoch");

                    b.Property<DateTime>("RoundTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("round_timestamp");

                    b.Property<BigInteger>("TipPaid")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("tip_paid");

                    b.Property<LedgerTransactionType>("discriminator")
                        .HasColumnType("ledger_transaction_type");

                    b.HasKey("StateVersion");

                    b.HasIndex("RoundTimestamp");

                    b.HasIndex("Epoch", "RoundInEpoch")
                        .IsUnique()
                        .HasFilter("index_in_round = 0");

                    b.ToTable("ledger_transactions");

                    b.HasDiscriminator<LedgerTransactionType>("discriminator");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransactionMarker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("StateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("state_version");

                    b.Property<LedgerTransactionMarkerType>("discriminator")
                        .HasColumnType("ledger_transaction_marker_type");

                    b.HasKey("Id");

                    b.HasIndex("StateVersion");

                    b.ToTable("ledger_transaction_markers");

                    b.HasDiscriminator<LedgerTransactionMarkerType>("discriminator");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.NetworkConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<AddressTypeDefinition[]>("AddressTypeDefinitions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("address_type_definitions");

                    b.Property<long>("GenesisEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("genesis_epoch");

                    b.Property<long>("GenesisRound")
                        .HasColumnType("bigint")
                        .HasColumnName("genesis_round");

                    b.Property<HrpDefinition>("HrpDefinition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hrp_definition");

                    b.Property<byte>("NetworkId")
                        .HasColumnType("smallint")
                        .HasColumnName("network_id");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("network_name");

                    b.Property<WellKnownAddresses>("WellKnownAddresses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("well_known_addresses");

                    b.HasKey("Id");

                    b.ToTable("network_configuration");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.NonFungibleIdData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<string>("NonFungibleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("non_fungible_id");

                    b.Property<long>("NonFungibleResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("non_fungible_resource_entity_id");

                    b.HasKey("Id");

                    b.HasIndex("NonFungibleResourceEntityId", "FromStateVersion");

                    b.HasIndex("NonFungibleResourceEntityId", "NonFungibleId", "FromStateVersion")
                        .IsUnique();

                    b.ToTable("non_fungible_id_data");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.NonFungibleIdDataHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<long>("NonFungibleIdDataId")
                        .HasColumnType("bigint")
                        .HasColumnName("non_fungible_id_data_id");

                    b.HasKey("Id");

                    b.HasIndex("NonFungibleIdDataId", "FromStateVersion");

                    b.ToTable("non_fungible_id_data_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.NonFungibleIdLocationHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("NonFungibleIdDataId")
                        .HasColumnType("bigint")
                        .HasColumnName("non_fungible_id_data_id");

                    b.Property<long>("VaultEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("vault_entity_id");

                    b.HasKey("Id");

                    b.HasIndex("NonFungibleIdDataId", "FromStateVersion");

                    b.ToTable("non_fungible_id_location_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.NonFungibleIdStoreHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<List<long>>("NonFungibleIdDataIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("non_fungible_id_data_ids");

                    b.Property<long>("NonFungibleResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("non_fungible_resource_entity_id");

                    b.HasKey("Id");

                    b.HasIndex("NonFungibleResourceEntityId", "FromStateVersion");

                    b.ToTable("non_fungible_id_store_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.NonFungibleSchemaHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("ResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.Property<SborTypeKind>("SborTypeKind")
                        .HasColumnType("sbor_type_kind")
                        .HasColumnName("sbor_type_kind");

                    b.Property<long>("SchemaDefiningEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("schema_defining_entity_id");

                    b.Property<byte[]>("SchemaHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("schema_hash");

                    b.Property<long>("TypeIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("type_index");

                    b.HasKey("Id");

                    b.HasIndex("ResourceEntityId", "FromStateVersion");

                    b.ToTable("non_fungible_schema_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.PackageBlueprintHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthTemplate")
                        .HasColumnType("jsonb")
                        .HasColumnName("auth_template");

                    b.Property<bool?>("AuthTemplateIsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("auth_template_is_locked");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<List<long>>("DependantEntityIds")
                        .HasColumnType("bigint[]")
                        .HasColumnName("dependant_entity_ids");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("PackageEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("package_entity_id");

                    b.Property<string>("RoyaltyConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("royalty_config");

                    b.Property<bool?>("RoyaltyConfigIsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("royalty_config_is_locked");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PackageEntityId", "FromStateVersion");

                    b.HasIndex("PackageEntityId", "Name", "Version", "FromStateVersion");

                    b.ToTable("package_blueprint_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.PackageCodeHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Code")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("PackageEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("package_entity_id");

                    b.HasKey("Id");

                    b.HasIndex("PackageEntityId", "FromStateVersion");

                    b.ToTable("package_code_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.PendingTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CommitTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("commit_timestamp");

                    b.Property<DateTime?>("FirstSeenInMempoolTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_in_mempool_timestamp");

                    b.Property<DateTime?>("FirstSubmittedToGatewayTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_submitted_to_gateway_timestamp");

                    b.Property<string>("IntentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intent_hash");

                    b.Property<DateTime?>("LastDroppedOutOfMempoolTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_missing_from_mempool_timestamp");

                    b.Property<string>("LastFailureReason")
                        .HasColumnType("text")
                        .HasColumnName("last_failure_reason");

                    b.Property<DateTime?>("LastFailureTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failure_timestamp");

                    b.Property<DateTime?>("LastSubmittedToGatewayTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_submitted_to_gateway_timestamp");

                    b.Property<string>("LastSubmittedToNodeName")
                        .HasColumnType("text")
                        .HasColumnName("last_submitted_to_node_name");

                    b.Property<DateTime?>("LastSubmittedToNodeTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_submitted_to_node_timestamp");

                    b.Property<byte[]>("NotarizedTransactionBlob")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("notarized_transaction_blob");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_hash");

                    b.Property<PendingTransactionStatus>("Status")
                        .HasColumnType("pending_transaction_status")
                        .HasColumnName("status");

                    b.Property<int>("SubmissionToNodesCount")
                        .HasColumnType("integer")
                        .HasColumnName("submission_count");

                    b.Property<bool>("SubmittedByThisGateway")
                        .HasColumnType("boolean")
                        .HasColumnName("submitted_by_this_gateway");

                    b.Property<uint>("VersionControl")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IntentHash");

                    b.HasIndex("PayloadHash")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("pending_transactions");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ResourceEntitySupplyHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("ResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.Property<BigInteger>("TotalBurned")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("total_burned");

                    b.Property<BigInteger>("TotalMinted")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("total_minted");

                    b.Property<BigInteger>("TotalSupply")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("total_supply");

                    b.HasKey("Id");

                    b.HasIndex("ResourceEntityId", "FromStateVersion");

                    b.ToTable("resource_entity_supply_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.SchemaHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<byte[]>("Schema")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("schema");

                    b.Property<byte[]>("SchemaHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("schema_hash");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "FromStateVersion");

                    b.HasIndex("SchemaHash", "FromStateVersion");

                    b.ToTable("schema_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.StateHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<StateType>("discriminator")
                        .HasColumnType("state_type");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "FromStateVersion");

                    b.ToTable("state_history");

                    b.HasDiscriminator<StateType>("discriminator");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ValidatorActiveSetHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint")
                        .HasColumnName("epoch");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<BigInteger>("Stake")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("stake");

                    b.Property<long>("ValidatorPublicKeyHistoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("validator_public_key_history_id");

                    b.HasKey("Id");

                    b.HasIndex("Epoch");

                    b.HasIndex("FromStateVersion");

                    b.HasIndex("ValidatorPublicKeyHistoryId");

                    b.ToTable("validator_active_set_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ValidatorEmissionStatistics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EpochNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("epoch_number");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("ProposalsMade")
                        .HasColumnType("bigint")
                        .HasColumnName("proposals_made");

                    b.Property<long>("ProposalsMissed")
                        .HasColumnType("bigint")
                        .HasColumnName("proposals_missed");

                    b.Property<long>("ValidatorEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("validator_entity_id");

                    b.HasKey("Id");

                    b.HasIndex("ValidatorEntityId", "EpochNumber");

                    b.ToTable("validator_emission_statistics");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ValidatorPublicKeyHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key");

                    b.Property<PublicKeyType>("KeyType")
                        .HasColumnType("public_key_type")
                        .HasColumnName("key_type");

                    b.Property<long>("ValidatorEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("validator_entity_id");

                    b.HasKey("Id");

                    b.HasIndex("ValidatorEntityId", "FromStateVersion");

                    b.HasIndex("ValidatorEntityId", "KeyType", "Key");

                    b.ToTable("validator_public_key_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GlobalAccessControllerEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.GlobalAccessController);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GlobalAccountEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.GlobalAccountComponent);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GlobalConsensusManager", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.GlobalConsensusManager);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GlobalFungibleResourceEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<int>("Divisibility")
                        .HasColumnType("integer")
                        .HasColumnName("divisibility");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.GlobalFungibleResource);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GlobalGenericComponentEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.GlobalGenericComponent);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GlobalIdentityEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.GlobalIdentity);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GlobalMultiResourcePoolEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.GlobalMultiResourcePool);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GlobalNonFungibleResourceEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<NonFungibleIdType>("NonFungibleIdType")
                        .HasColumnType("non_fungible_id_type")
                        .HasColumnName("non_fungible_id_type");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.GlobalNonFungibleResource);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GlobalOneResourcePoolEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.GlobalOneResourcePool);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GlobalPackageEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<PackageVmType>("VmType")
                        .HasColumnType("package_vm_type")
                        .HasColumnName("vm_type");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.GlobalPackage);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GlobalTransactionTrackerEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.GlobalTransactionTracker);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GlobalTwoResourcePoolEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.GlobalTwoResourcePool);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GlobalValidatorEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("LockedOwnerStakeUnitVault")
                        .HasColumnType("bigint")
                        .HasColumnName("locked_owner_stake_unit_vault_entity_id");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long>("PendingOwnerStakeUnitUnlockVault")
                        .HasColumnType("bigint")
                        .HasColumnName("pending_owner_stake_unit_unlock_vault_entity_id");

                    b.Property<long>("PendingXrdWithdrawVault")
                        .HasColumnType("bigint")
                        .HasColumnName("pending_xrd_withdraw_vault_entity_id");

                    b.Property<long>("StakeVaultEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("stake_vault_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.GlobalValidator);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.InternalFungibleVaultEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long>("ResourceEntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.Property<long?>("RoyaltyVaultOfEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("royalty_vault_of_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.InternalFungibleVault);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.InternalGenericComponentEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.InternalGenericComponent);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.InternalKeyValueStoreEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.InternalKeyValueStore);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.InternalNonFungibleVaultEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<string>("BlueprintVersion")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_version");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long>("ResourceEntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.InternalNonFungibleVault);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityFungibleResourceAggregatedVaultsHistory", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityResourceAggregatedVaultsHistory");

                    b.Property<BigInteger>("Balance")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.ToTable("entity_resource_aggregated_vaults_history");

                    b.HasDiscriminator().HasValue(ResourceType.Fungible);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityNonFungibleResourceAggregatedVaultsHistory", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityResourceAggregatedVaultsHistory");

                    b.Property<long>("TotalCount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_count");

                    b.ToTable("entity_resource_aggregated_vaults_history");

                    b.HasDiscriminator().HasValue(ResourceType.NonFungible);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityFungibleVaultHistory", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityVaultHistory");

                    b.Property<BigInteger>("Balance")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<bool>("IsRoyaltyVault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_royalty_vault");

                    b.ToTable("entity_vault_history");

                    b.HasDiscriminator().HasValue(ResourceType.Fungible);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityNonFungibleVaultHistory", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityVaultHistory");

                    b.Property<List<long>>("NonFungibleIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("non_fungible_ids");

                    b.ToTable("entity_vault_history");

                    b.HasDiscriminator().HasValue(ResourceType.NonFungible);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.GenesisLedgerTransaction", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransaction");

                    b.ToTable("ledger_transactions");

                    b.HasDiscriminator().HasValue(LedgerTransactionType.Genesis);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.RoundUpdateLedgerTransaction", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransaction");

                    b.ToTable("ledger_transactions");

                    b.HasDiscriminator().HasValue(LedgerTransactionType.RoundUpdate);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.UserLedgerTransaction", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransaction");

                    b.Property<string>("IntentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intent_hash");

                    b.Property<string>("Message")
                        .HasColumnType("jsonb")
                        .HasColumnName("message");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_hash");

                    b.Property<byte[]>("RawPayload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("raw_payload");

                    b.Property<string>("SignedIntentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signed_intent_hash");

                    b.HasIndex("IntentHash")
                        .HasFilter("intent_hash IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("IntentHash"), "hash");

                    b.ToTable("ledger_transactions");

                    b.HasDiscriminator().HasValue(LedgerTransactionType.User);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.AffectedGlobalEntityTransactionMarker", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransactionMarker");

                    b.Property<long>("EntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.HasIndex("EntityId", "StateVersion")
                        .HasFilter("discriminator = 'affected_global_entity'");

                    b.ToTable("ledger_transaction_markers");

                    b.HasDiscriminator().HasValue(LedgerTransactionMarkerType.AffectedGlobalEntity);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EventLedgerTransactionMarker", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransactionMarker");

                    b.Property<long>("EntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<LedgerTransactionMarkerEventType>("EventType")
                        .HasColumnType("ledger_transaction_marker_event_type")
                        .HasColumnName("event_type");

                    b.Property<BigInteger>("Quantity")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<long>("ResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.HasIndex("EventType", "EntityId", "StateVersion")
                        .HasFilter("discriminator = 'event'");

                    b.ToTable("ledger_transaction_markers");

                    b.HasDiscriminator().HasValue(LedgerTransactionMarkerType.Event);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ManifestAddressLedgerTransactionMarker", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransactionMarker");

                    b.Property<long>("EntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<LedgerTransactionMarkerOperationType>("OperationType")
                        .HasColumnType("ledger_transaction_marker_operation_type")
                        .HasColumnName("operation_type");

                    b.HasIndex("OperationType", "EntityId", "StateVersion")
                        .HasFilter("discriminator = 'manifest_address'");

                    b.ToTable("ledger_transaction_markers");

                    b.HasDiscriminator().HasValue(LedgerTransactionMarkerType.ManifestAddress);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.OriginLedgerTransactionMarker", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransactionMarker");

                    b.Property<LedgerTransactionMarkerOriginType>("OriginType")
                        .HasColumnType("ledger_transaction_marker_origin_type")
                        .HasColumnName("origin_type");

                    b.HasIndex("OriginType", "StateVersion")
                        .HasFilter("discriminator = 'origin'");

                    b.ToTable("ledger_transaction_markers");

                    b.HasDiscriminator().HasValue(LedgerTransactionMarkerType.Origin);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.JsonStateHistory", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.StateHistory");

                    b.Property<string>("JsonState")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json_state");

                    b.ToTable("state_history");

                    b.HasDiscriminator().HasValue(StateType.Json);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.SborStateHistory", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.StateHistory");

                    b.Property<byte[]>("SborState")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sbor_state");

                    b.Property<SborTypeKind>("SborTypeKind")
                        .HasColumnType("sbor_type_kind")
                        .HasColumnName("sbor_type_kind");

                    b.Property<long>("SchemaDefiningEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("schema_defining_entity_id");

                    b.Property<byte[]>("SchemaHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("schema_hash");

                    b.Property<long>("TypeIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("type_index");

                    b.ToTable("state_history");

                    b.HasDiscriminator().HasValue(StateType.Sbor);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransaction", b =>
                {
                    b.OwnsOne("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerHashes", "LedgerHashes", b1 =>
                        {
                            b1.Property<long>("LedgerTransactionStateVersion")
                                .HasColumnType("bigint");

                            b1.Property<string>("ReceiptTreeHash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("receipt_tree_hash");

                            b1.Property<string>("StateTreeHash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("state_tree_hash");

                            b1.Property<string>("TransactionTreeHash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("transaction_tree_hash");

                            b1.HasKey("LedgerTransactionStateVersion");

                            b1.ToTable("ledger_transactions");

                            b1.WithOwner()
                                .HasForeignKey("LedgerTransactionStateVersion");
                        });

                    b.OwnsOne("RadixDlt.NetworkGateway.PostgresIntegration.Models.TransactionReceipt", "EngineReceipt", b1 =>
                        {
                            b1.Property<long>("LedgerTransactionStateVersion")
                                .HasColumnType("bigint");

                            b1.Property<string>("CostingParameters")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("receipt_costing_parameters");

                            b1.Property<string>("ErrorMessage")
                                .HasColumnType("text")
                                .HasColumnName("receipt_error_message");

                            b1.Property<string>("FeeDestination")
                                .HasColumnType("jsonb")
                                .HasColumnName("receipt_fee_destination");

                            b1.Property<string>("FeeSource")
                                .HasColumnType("jsonb")
                                .HasColumnName("receipt_fee_source");

                            b1.Property<string>("FeeSummary")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("receipt_fee_summary");

                            b1.Property<string>("NextEpoch")
                                .HasColumnType("jsonb")
                                .HasColumnName("receipt_next_epoch");

                            b1.Property<string>("Output")
                                .HasColumnType("jsonb")
                                .HasColumnName("receipt_output");

                            b1.Property<string>("StateUpdates")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("receipt_state_updates");

                            b1.Property<LedgerTransactionStatus>("Status")
                                .HasColumnType("ledger_transaction_status")
                                .HasColumnName("receipt_status");

                            b1.HasKey("LedgerTransactionStateVersion");

                            b1.ToTable("ledger_transactions");

                            b1.WithOwner()
                                .HasForeignKey("LedgerTransactionStateVersion");

                            b1.OwnsOne("RadixDlt.NetworkGateway.PostgresIntegration.Models.ReceiptEvents", "Events", b2 =>
                                {
                                    b2.Property<long>("TransactionReceiptLedgerTransactionStateVersion")
                                        .HasColumnType("bigint");

                                    b2.Property<string[]>("Emitters")
                                        .IsRequired()
                                        .HasColumnType("jsonb[]")
                                        .HasColumnName("receipt_event_emitters");

                                    b2.Property<string[]>("Names")
                                        .IsRequired()
                                        .HasColumnType("text[]")
                                        .HasColumnName("receipt_event_names");

                                    b2.Property<SborTypeKind[]>("SborTypeKinds")
                                        .IsRequired()
                                        .HasColumnType("sbor_type_kind[]")
                                        .HasColumnName("receipt_event_sbor_type_kinds");

                                    b2.Property<byte[][]>("Sbors")
                                        .IsRequired()
                                        .HasColumnType("bytea[]")
                                        .HasColumnName("receipt_event_sbors");

                                    b2.Property<long[]>("SchemaEntityIds")
                                        .IsRequired()
                                        .HasColumnType("bigint[]")
                                        .HasColumnName("receipt_event_schema_entity_ids");

                                    b2.Property<byte[][]>("SchemaHashes")
                                        .IsRequired()
                                        .HasColumnType("bytea[]")
                                        .HasColumnName("receipt_event_schema_hashes");

                                    b2.Property<long[]>("TypeIndexes")
                                        .IsRequired()
                                        .HasColumnType("bigint[]")
                                        .HasColumnName("receipt_event_type_indexes");

                                    b2.HasKey("TransactionReceiptLedgerTransactionStateVersion");

                                    b2.ToTable("ledger_transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("TransactionReceiptLedgerTransactionStateVersion");
                                });

                            b1.Navigation("Events")
                                .IsRequired();
                        });

                    b.Navigation("EngineReceipt")
                        .IsRequired();

                    b.Navigation("LedgerHashes")
                        .IsRequired();
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ValidatorActiveSetHistory", b =>
                {
                    b.HasOne("RadixDlt.NetworkGateway.PostgresIntegration.Models.ValidatorPublicKeyHistory", "PublicKey")
                        .WithMany()
                        .HasForeignKey("ValidatorPublicKeyHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicKey");
                });
#pragma warning restore 612, 618
        }
    }
}
