/* Copyright 2021 Radix Publishing Ltd incorporated in Jersey (Channel Islands).
 *
 * Licensed under the Radix License, Version 1.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the License at:
 *
 * radixfoundation.org/licenses/LICENSE-v1
 *
 * The Licensor hereby grants permission for the Canonical version of the Work to be
 * published, distributed and used under or by reference to the Licensor’s trademark
 * Radix ® and use of any unregistered trade names, logos or get-up.
 *
 * The Licensor provides the Work (and each Contributor provides its Contributions) on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied,
 * including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT,
 * MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * Whilst the Work is capable of being deployed, used and adopted (instantiated) to create
 * a distributed ledger it is your responsibility to test and validate the code, together
 * with all logic and performance of that code under all foreseeable scenarios.
 *
 * The Licensor does not make or purport to make and hereby excludes liability for all
 * and any representation, warranty or undertaking in any form whatsoever, whether express
 * or implied, to any entity or person, including any representation, warranty or
 * undertaking, as to the functionality security use, value or other characteristics of
 * any distributed ledger nor in respect the functioning or value of any tokens which may
 * be created stored or transferred using the Work. The Licensor does not warrant that the
 * Work or any use of the Work complies with any law or regulation in any territory where
 * it may be implemented or used or that it will be appropriate for any specific purpose.
 *
 * Neither the licensor nor any current or former employees, officers, directors, partners,
 * trustees, representatives, agents, advisors, contractors, or volunteers of the Licensor
 * shall be liable for any direct or indirect, special, incidental, consequential or other
 * losses of any kind, in tort, contract or otherwise (including but not limited to loss
 * of revenue, income or profits, or loss of use or data, or loss of reputation, or loss
 * of any economic or other opportunity of whatsoever nature or howsoever arising), arising
 * out of or in connection with (without limitation of any use, misuse, of any ledger system
 * or use made or its functionality or any performance or operation of any code or protocol
 * caused by bugs or programming or logic errors or otherwise);
 *
 * A. any offer, purchase, holding, use, sale, exchange or transmission of any
 * cryptographic keys, tokens or assets created, exchanged, stored or arising from any
 * interaction with the Work;
 *
 * B. any failure in a transmission or loss of any token or assets keys or other digital
 * artefacts due to errors in transmission;
 *
 * C. bugs, hacks, logic errors or faults in the Work or any communication;
 *
 * D. system software or apparatus including but not limited to losses caused by errors
 * in holding or transmitting tokens by any third-party;
 *
 * E. breaches or failure of security including hacker attacks, loss or disclosure of
 * password, loss of private key, unauthorised use or misuse of such passwords or keys;
 *
 * F. any losses including loss of anticipated savings or other benefits resulting from
 * use of the Work or any changes to the Work (however implemented).
 *
 * You are solely responsible for; testing, validating and evaluation of all operation
 * logic, functionality, security and appropriateness of using the Work for any commercial
 * or non-commercial purpose and for any reproduction or redistribution by You of the
 * Work. You assume all risks associated with Your use of the Work and the exercise of
 * permissions under this License.
 */

// <auto-generated />
using System;
using System.Collections.Generic;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RadixDlt.NetworkGateway.Abstractions.Addressing;
using RadixDlt.NetworkGateway.Abstractions.Model;
using RadixDlt.NetworkGateway.PostgresIntegration;
using RadixDlt.NetworkGateway.PostgresIntegration.Models;

#nullable disable

namespace RadixDlt.NetworkGateway.PostgresIntegration.Migrations
{
    [DbContext(typeof(MigrationsDbContext))]
    partial class MigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "access_rules_chain_subtype", new[] { "none", "resource_manager_vault_access_rules_chain" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "entity_type", new[] { "epoch_manager", "fungible_resource", "non_fungible_resource", "normal_component", "account_component", "package", "key_value_store", "vault", "clock", "validator", "access_controller", "identity" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ledger_transaction_kind_filter_constraint", new[] { "user", "epoch_change" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ledger_transaction_status", new[] { "succeeded", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ledger_transaction_type", new[] { "user", "validator", "system" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "non_fungible_id_type", new[] { "string", "integer", "bytes", "uuid" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pending_transaction_status", new[] { "submitted_or_known_in_node_mempool", "missing", "rejected_temporarily", "rejected_permanently", "committed_success", "committed_failure" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public_key_type", new[] { "ecdsa_secp256k1", "eddsa_ed25519" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "resource_type", new[] { "fungible", "non_fungible" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Address")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("address");

                    b.Property<List<long>>("AncestorIds")
                        .HasColumnType("bigint[]")
                        .HasColumnName("ancestor_ids");

                    b.Property<List<long>>("CorrelatedEntities")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("correlated_entities");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<string>("GlobalAddress")
                        .HasColumnType("text")
                        .HasColumnName("global_address");

                    b.Property<long?>("GlobalAncestorId")
                        .HasColumnType("bigint")
                        .HasColumnName("global_ancestor_id");

                    b.Property<long?>("OwnerAncestorId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_ancestor_id");

                    b.Property<long?>("ParentAncestorId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_ancestor_id");

                    b.Property<EntityType>("discriminator")
                        .HasColumnType("entity_type");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Address"), "hash");

                    b.HasIndex("GlobalAddress")
                        .HasFilter("global_address IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("GlobalAddress"), "hash");

                    b.ToTable("entities");

                    b.HasDiscriminator<EntityType>("discriminator");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityAccessRulesChainHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessRulesChain")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("access_rules_chain");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<AccessRulesChainSubtype>("Subtype")
                        .HasColumnType("access_rules_chain_subtype")
                        .HasColumnName("subtype");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Subtype", "FromStateVersion");

                    b.ToTable("entity_access_rules_chain_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityMetadataHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<List<string>>("Keys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("keys");

                    b.Property<List<long>>("UpdatedAtStateVersions")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("updated_at_state_versions");

                    b.Property<List<byte[]>>("Values")
                        .IsRequired()
                        .HasColumnType("bytea[]")
                        .HasColumnName("values");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "FromStateVersion");

                    b.ToTable("entity_metadata_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityResourceAggregateHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<List<long>>("FungibleResourceEntityIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("fungible_resource_entity_ids");

                    b.Property<List<long>>("FungibleResourceSignificantUpdateStateVersions")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("fungible_resource_significant_update_state_versions");

                    b.Property<List<long>>("NonFungibleResourceEntityIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("non_fungible_resource_entity_ids");

                    b.Property<List<long>>("NonFungibleResourceSignificantUpdateStateVersions")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("non_fungible_resource_significant_update_state_versions");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "FromStateVersion");

                    b.ToTable("entity_resource_aggregate_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityResourceAggregatedVaultsHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("ResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.Property<string>("TmpTmpRemoveMeOnceTxEventsBecomeAvailable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tmp_tmp_remove_me_once_tx_events_become_available");

                    b.Property<ResourceType>("discriminator")
                        .HasColumnType("resource_type");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "ResourceEntityId", "FromStateVersion");

                    b.ToTable("entity_resource_aggregated_vaults_history");

                    b.HasDiscriminator<ResourceType>("discriminator");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityResourceVaultAggregateHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("ResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.Property<List<long>>("VaultEntityIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("vault_entity_ids");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "ResourceEntityId", "FromStateVersion");

                    b.ToTable("entity_resource_vault_aggregate_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityStateHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "FromStateVersion");

                    b.ToTable("entity_state_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityVaultHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("GlobalEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("global_entity_id");

                    b.Property<long>("OwnerEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_entity_id");

                    b.Property<long>("ResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.Property<long>("VaultEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("vault_entity_id");

                    b.Property<ResourceType>("discriminator")
                        .HasColumnType("resource_type");

                    b.HasKey("Id");

                    b.HasIndex("GlobalEntityId", "VaultEntityId", "FromStateVersion");

                    b.HasIndex("OwnerEntityId", "VaultEntityId", "FromStateVersion");

                    b.ToTable("entity_vault_history");

                    b.HasDiscriminator<ResourceType>("discriminator");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastUpdated")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<long>("TargetStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("sync_status_target_state_version");

                    b.Property<long>("TopOfLedgerStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("top_of_ledger_state_version");

                    b.HasKey("Id");

                    b.HasIndex("TopOfLedgerStateVersion");

                    b.ToTable("ledger_status");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransaction", b =>
                {
                    b.Property<long>("StateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("state_version");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint")
                        .HasColumnName("epoch");

                    b.Property<BigInteger?>("FeePaid")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("fee_paid");

                    b.Property<long>("IndexInEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("index_in_epoch");

                    b.Property<long>("IndexInRound")
                        .HasColumnType("bigint")
                        .HasColumnName("index_in_round");

                    b.Property<bool>("IsEndOfEpoch")
                        .HasColumnType("boolean")
                        .HasColumnName("is_end_of_epoch");

                    b.Property<LedgerTransactionKindFilterConstraint?>("KindFilterConstraint")
                        .HasColumnType("ledger_transaction_kind_filter_constraint")
                        .HasColumnName("kind_filter_constraint");

                    b.Property<byte[]>("Message")
                        .HasColumnType("bytea")
                        .HasColumnName("message");

                    b.Property<DateTime>("NormalizedRoundTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("normalized_round_timestamp");

                    b.Property<byte[]>("RawPayload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("raw_payload");

                    b.Property<List<long>>("ReferencedEntities")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("referenced_entities");

                    b.Property<long>("RoundInEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("round_in_epoch");

                    b.Property<DateTime>("RoundTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("round_timestamp");

                    b.Property<BigInteger?>("TipPaid")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("tip_paid");

                    b.Property<byte[]>("TransactionAccumulator")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("transaction_accumulator");

                    b.Property<LedgerTransactionType>("discriminator")
                        .HasColumnType("ledger_transaction_type");

                    b.HasKey("StateVersion");

                    b.HasIndex("RoundTimestamp");

                    b.HasIndex("Epoch", "RoundInEpoch")
                        .IsUnique()
                        .HasFilter("index_in_round = 0");

                    b.HasIndex("KindFilterConstraint", "StateVersion")
                        .HasFilter("kind_filter_constraint IS NOT NULL");

                    b.ToTable("ledger_transactions");

                    b.HasDiscriminator<LedgerTransactionType>("discriminator");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.NetworkConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<AddressTypeDefinition[]>("AddressTypeDefinitions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("address_type_definitions");

                    b.Property<HrpDefinition>("HrpDefinition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hrp_definition");

                    b.Property<byte>("NetworkId")
                        .HasColumnType("smallint")
                        .HasColumnName("network_id");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("network_name");

                    b.Property<WellKnownAddresses>("WellKnownAddresses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("well_known_addresses");

                    b.HasKey("Id");

                    b.ToTable("network_configuration");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.NonFungibleIdData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("KeyValueStoreEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("key_value_store_entity_id");

                    b.Property<string>("NonFungibleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("non_fungible_id");

                    b.Property<long>("NonFungibleResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("non_fungible_resource_entity_id");

                    b.HasKey("Id");

                    b.HasIndex("NonFungibleResourceEntityId", "FromStateVersion");

                    b.HasIndex("NonFungibleResourceEntityId", "NonFungibleId", "FromStateVersion");

                    b.ToTable("non_fungible_id_data");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.NonFungibleIdDataHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("NonFungibleIdDataId")
                        .HasColumnType("bigint")
                        .HasColumnName("non_fungible_id_data_id");

                    b.HasKey("Id");

                    b.HasIndex("NonFungibleIdDataId", "FromStateVersion");

                    b.ToTable("non_fungible_id_data_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.NonFungibleIdStoreHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("KeyValueStoreEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("key_value_store_entity_id");

                    b.Property<List<long>>("NonFungibleIdDataIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("non_fungible_id_data_ids");

                    b.Property<long>("NonFungibleResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("non_fungible_resource_entity_id");

                    b.HasKey("Id");

                    b.HasIndex("NonFungibleResourceEntityId", "FromStateVersion");

                    b.ToTable("non_fungible_id_store_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.PendingTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CommitTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("commit_timestamp");

                    b.Property<DateTime?>("FirstSeenInMempoolTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_in_mempool_timestamp");

                    b.Property<DateTime?>("FirstSubmittedToGatewayTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_submitted_to_gateway_timestamp");

                    b.Property<byte[]>("IntentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("intent_hash");

                    b.Property<DateTime?>("LastDroppedOutOfMempoolTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_missing_from_mempool_timestamp");

                    b.Property<string>("LastFailureReason")
                        .HasColumnType("text")
                        .HasColumnName("last_failure_reason");

                    b.Property<DateTime?>("LastFailureTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failure_timestamp");

                    b.Property<DateTime?>("LastSubmittedToGatewayTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_submitted_to_gateway_timestamp");

                    b.Property<string>("LastSubmittedToNodeName")
                        .HasColumnType("text")
                        .HasColumnName("last_submitted_to_node_name");

                    b.Property<DateTime?>("LastSubmittedToNodeTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_submitted_to_node_timestamp");

                    b.Property<byte[]>("NotarizedTransactionBlob")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("notarized_transaction_blob");

                    b.Property<byte[]>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_hash");

                    b.Property<PendingTransactionStatus>("Status")
                        .HasColumnType("pending_transaction_status")
                        .HasColumnName("status");

                    b.Property<int>("SubmissionToNodesCount")
                        .HasColumnType("integer")
                        .HasColumnName("submission_count");

                    b.Property<bool>("SubmittedByThisGateway")
                        .HasColumnType("boolean")
                        .HasColumnName("submitted_by_this_gateway");

                    b.Property<uint>("VersionControl")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IntentHash");

                    b.HasIndex("PayloadHash")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("pending_transactions");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ResourceEntitySupplyHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<long>("ResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.Property<BigInteger>("TotalBurnt")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("total_burnt");

                    b.Property<BigInteger>("TotalMinted")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("total_minted");

                    b.Property<BigInteger>("TotalSupply")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("total_supply");

                    b.HasKey("Id");

                    b.HasIndex("ResourceEntityId", "FromStateVersion");

                    b.ToTable("resource_entity_supply_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ValidatorActiveSetHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint")
                        .HasColumnName("epoch");

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<BigInteger>("Stake")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("stake");

                    b.Property<long>("ValidatorPublicKeyHistoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("validator_public_key_history_id");

                    b.HasKey("Id");

                    b.HasIndex("Epoch");

                    b.HasIndex("FromStateVersion");

                    b.HasIndex("ValidatorPublicKeyHistoryId");

                    b.ToTable("validator_active_set_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ValidatorPublicKeyHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_state_version");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key");

                    b.Property<PublicKeyType>("KeyType")
                        .HasColumnType("public_key_type")
                        .HasColumnName("key_type");

                    b.Property<long>("ValidatorEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("validator_entity_id");

                    b.HasKey("Id");

                    b.HasIndex("ValidatorEntityId", "FromStateVersion");

                    b.HasIndex("ValidatorEntityId", "KeyType", "Key");

                    b.ToTable("validator_public_key_history");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.AccessControllerEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long?>("RoyaltyVaultEntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("royalty_vault_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.AccessController);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.AccountComponentEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long?>("RoyaltyVaultEntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("royalty_vault_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.AccountComponent);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ClockEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long?>("RoyaltyVaultEntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("royalty_vault_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.Clock);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EpochManagerEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long?>("RoyaltyVaultEntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("royalty_vault_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.EpochManager);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.FungibleResourceEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<int>("Divisibility")
                        .HasColumnType("integer")
                        .HasColumnName("divisibility");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long?>("RoyaltyVaultEntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("royalty_vault_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.FungibleResource);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.IdentityEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long?>("RoyaltyVaultEntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("royalty_vault_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.Identity);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.KeyValueStoreEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<long?>("StoreOfNonFungibleResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_of_non_fungible_resource_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.KeyValueStore);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.NonFungibleResourceEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<NonFungibleIdType>("NonFungibleIdType")
                        .HasColumnType("non_fungible_id_type")
                        .HasColumnName("non_fungible_id_type");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long?>("RoyaltyVaultEntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("royalty_vault_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.NonFungibleResource);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.NormalComponentEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long?>("RoyaltyVaultEntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("royalty_vault_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.NormalComponent);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.PackageEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<byte[]>("Code")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_type");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long?>("RoyaltyVaultEntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("royalty_vault_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.Package);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ValidatorEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<long>("EpochManagerEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("epoch_manager_entity_id");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long?>("RoyaltyVaultEntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("royalty_vault_entity_id");

                    b.Property<long>("StakeVaultEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("stake_vault_entity_id");

                    b.Property<long>("UnstakeVaultEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("unstake_vault_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.Validator);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.VaultEntity", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.Entity");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("blueprint_name");

                    b.Property<long>("PackageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long>("ResourceEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_entity_id");

                    b.Property<long?>("RoyaltyVaultEntityId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("royalty_vault_entity_id");

                    b.Property<long?>("RoyaltyVaultOfEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("royalty_vault_of_entity_id");

                    b.ToTable("entities");

                    b.HasDiscriminator().HasValue(EntityType.Vault);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityFungibleResourceAggregatedVaultsHistory", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityResourceAggregatedVaultsHistory");

                    b.Property<BigInteger>("Balance")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.ToTable("entity_resource_aggregated_vaults_history");

                    b.HasDiscriminator().HasValue(ResourceType.Fungible);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityNonFungibleResourceAggregatedVaultsHistory", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityResourceAggregatedVaultsHistory");

                    b.Property<long>("TotalCount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_count");

                    b.ToTable("entity_resource_aggregated_vaults_history");

                    b.HasDiscriminator().HasValue(ResourceType.NonFungible);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityFungibleVaultHistory", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityVaultHistory");

                    b.Property<BigInteger>("Balance")
                        .HasPrecision(1000)
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<bool>("IsRoyaltyVault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_royalty_vault");

                    b.ToTable("entity_vault_history");

                    b.HasDiscriminator().HasValue(ResourceType.Fungible);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityNonFungibleVaultHistory", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.EntityVaultHistory");

                    b.Property<List<long>>("NonFungibleIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("non_fungible_ids");

                    b.ToTable("entity_vault_history");

                    b.HasDiscriminator().HasValue(ResourceType.NonFungible);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.SystemLedgerTransaction", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransaction");

                    b.ToTable("ledger_transactions");

                    b.HasDiscriminator().HasValue(LedgerTransactionType.System);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.UserLedgerTransaction", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransaction");

                    b.Property<byte[]>("IntentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("intent_hash");

                    b.Property<byte[]>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_hash");

                    b.Property<byte[]>("SignedIntentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("signed_intent_hash");

                    b.HasIndex("IntentHash")
                        .HasFilter("intent_hash IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("IntentHash"), "hash");

                    b.ToTable("ledger_transactions");

                    b.HasDiscriminator().HasValue(LedgerTransactionType.User);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ValidatorLedgerTransaction", b =>
                {
                    b.HasBaseType("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransaction");

                    b.ToTable("ledger_transactions");

                    b.HasDiscriminator().HasValue(LedgerTransactionType.Validator);
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerStatus", b =>
                {
                    b.HasOne("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransaction", "TopOfLedgerTransaction")
                        .WithMany()
                        .HasForeignKey("TopOfLedgerStateVersion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TopOfLedgerTransaction");
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.LedgerTransaction", b =>
                {
                    b.OwnsOne("RadixDlt.NetworkGateway.PostgresIntegration.Models.TransactionReceipt", "EngineReceipt", b1 =>
                        {
                            b1.Property<long>("LedgerTransactionStateVersion")
                                .HasColumnType("bigint");

                            b1.Property<string>("ErrorMessage")
                                .HasColumnType("text")
                                .HasColumnName("receipt_error_message");

                            b1.Property<string>("Events")
                                .HasColumnType("jsonb")
                                .HasColumnName("receipt_events");

                            b1.Property<string>("FeeSummary")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("receipt_fee_summary");

                            b1.Property<string>("Items")
                                .HasColumnType("jsonb")
                                .HasColumnName("receipt_items");

                            b1.Property<string>("NextEpoch")
                                .HasColumnType("jsonb")
                                .HasColumnName("receipt_next_epoch");

                            b1.Property<string>("StateUpdates")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("receipt_state_updates");

                            b1.Property<LedgerTransactionStatus>("Status")
                                .HasColumnType("ledger_transaction_status")
                                .HasColumnName("receipt_status");

                            b1.HasKey("LedgerTransactionStateVersion");

                            b1.ToTable("ledger_transactions");

                            b1.WithOwner()
                                .HasForeignKey("LedgerTransactionStateVersion");
                        });

                    b.Navigation("EngineReceipt")
                        .IsRequired();
                });

            modelBuilder.Entity("RadixDlt.NetworkGateway.PostgresIntegration.Models.ValidatorActiveSetHistory", b =>
                {
                    b.HasOne("RadixDlt.NetworkGateway.PostgresIntegration.Models.ValidatorPublicKeyHistory", "PublicKey")
                        .WithMany()
                        .HasForeignKey("ValidatorPublicKeyHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicKey");
                });
#pragma warning restore 612, 618
        }
    }
}
