name: Run performance benchmark on an ephemeral environment

on:
  push:
    branches:
      - feature/github-actions-benchmark-job

jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-22.04
    steps:
      - name: cancel running workflows
        uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5
        with:
          access_token: ${{github.token}}
  ephemeral-benchmark:
    runs-on: ubuntu-22.04
    needs:
      - docker-gateway-api-gcr
      - docker-data-aggregator-gcr
      - docker-database-migrations-gcr
      - setup-tags
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Export branch name in github's environment
        run: |
          echo "GATEWAY_BRANCH=$GITHUB_HEAD_REF" >> $GITHUB_ENV
      - name: Extract the gateway and node tags from ci.env
        run: |
          export $(grep -v '^#' ./deployment/ci.env | xargs)
          echo "FULLNODE_VERSION=$FULLNODE_VERSION" >> $GITHUB_ENV
          echo "POSTGRES_VERSION=$POSTGRES_VERSION" >> $GITHUB_ENV
      - name: Deploy and run benchmark on an ephemeral network
        uses: toptal/jenkins-job-trigger-action@649c04c83c099c759aba134bf78138a303ec095f
        with:
          jenkins_url: "${{ secrets.JENKINS_URL }}"
          jenkins_user: ${{ secrets.JENKINS_USER }}
          jenkins_token: ${{ secrets.BABYLON_NODE_JENKINS_API_TOKEN }}
          job_name: "ephemeral-deployments/job/ephemeral-env-gateway-benchmark"
          job_params: |
            {
              "gatewayDockerTag": "${{ needs.setup-tags.outputs.gateway-api-tag }}",
              "gatewayBranch": "${{ env.GATEWAY_BRANCH }}",
              "nodeDockerTag": "${{ env.FULLNODE_VERSION }}",
              "postgresVersion": "${{ env.POSTGRES_VERSION }}"
            }
          job_timeout: "3600"
