name: Publish TypeScript Gateway SDK

on:
  workflow_dispatch:
    inputs:
      package_version_number:
        description: "Package version number"
        required: true

jobs:
  publish-gateway-sdk-npmjs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk/typescript
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: RDXWorks-actions/checkout@main

      - name: Use Node.js
        uses: RDXWorks-actions/setup-node@main
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      
      - name: Upgrade npm
        run: npm i -g npm@^11.5.1
      
      - name: Build alphanet-gateway-sdk
        env:
          VITE_SDK_VERSION: ${{ github.event.inputs.package_version_number || steps.setup_tags.outputs.version-tag }}
        run: |
          npm ci
          npm run build
          npm run test

      - name: Setup tags for npm
        id: setup_tags
        uses: ./.github/actions/set-variables
        with:
          github_event_name: ${{ github.event_name }}
          github_action_name: ${{ github.event.action}}

      - name: Update package.json version
        uses: RDXWorks-actions/action-set-json-field@master
        with:
          file: ./sdk/typescript/package.json
          field: version
          value: ${{ github.event.inputs.package_version_number || steps.setup_tags.outputs.version-tag }}

      - name: Publish
        run: env -u NODE_AUTH_TOKEN -u NPM_CONFIG_USERCONFIG npm publish --access public
  