name: Re-usable Release Drafter

on:
  workflow_call:

jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    steps:
      - uses: RDXWorks-actions/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
